"""Artifact schema rows for the reusable governance platform blueprint."""

from __future__ import annotations

from .contract_registry_models import (
    CONTRACT_REGISTRY_CONTRACT_ID,
    CONTRACT_REGISTRY_SCHEMA_VERSION,
)
from .contracts import ArtifactSchemaSpec


def artifact_schemas() -> tuple[ArtifactSchemaSpec, ...]:
    """Return the durable artifact schema matrix for already-real platform families."""
    return (
        ArtifactSchemaSpec(
            contract_id=CONTRACT_REGISTRY_CONTRACT_ID,
            owner_layer="governance_runtime",
            purpose=(
                "Repo-owned JSONL registry of shared runtime contracts and artifact "
                "schemas, including owner paths, schema versions, fixture roots, "
                "and parity commands."
            ),
            schema_version=CONTRACT_REGISTRY_SCHEMA_VERSION,
            emitter_path="dev/scripts/devctl/platform/contract_registry.py",
            constants_module="dev.scripts.devctl.platform.contract_registry_models",
            contract_id_attr="CONTRACT_REGISTRY_CONTRACT_ID",
            schema_version_attr="CONTRACT_REGISTRY_SCHEMA_VERSION",
            compatibility_window="stable for repo-owned registry rows; additive fields only",
            migration_path="Add registry fields additively and update registry closure plus fixture expectations before changing consumers.",
            rollback_path="Restore prior registry row shape and closure expectations before removing consumer support.",
        ),
        ArtifactSchemaSpec(
            contract_id="ProbeReport",
            owner_layer="governance_core",
            purpose="Canonical aggregate probe-report payload emitted by `devctl probe-report`.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/review_probe_report.py",
            constants_module="dev.scripts.devctl.runtime.finding_contracts",
            contract_id_attr="PROBE_REPORT_CONTRACT_ID",
            schema_version_attr="PROBE_REPORT_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 P0/P1; additive changes only",
            migration_path="Add new fields additively, then update renderers/tests before changing consumers.",
            rollback_path="Keep previous schema constants and writer behavior until consumers are restored.",
        ),
        ArtifactSchemaSpec(
            contract_id="ReviewPacket",
            owner_layer="governance_core",
            purpose="Hotspot-ranked review packet projection for probe-report follow-up.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/probe_topology/builder.py",
            constants_module="dev.scripts.devctl.runtime.finding_contracts",
            contract_id_attr="REVIEW_PACKET_CONTRACT_ID",
            schema_version_attr="REVIEW_PACKET_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 P0/P1; additive changes only",
            migration_path="Update packet builders and markdown/JSON renderers together before expanding fields.",
            rollback_path="Restore prior packet constants and artifact writers before removing consumers.",
        ),
        ArtifactSchemaSpec(
            contract_id="ReviewerAuditReceipt",
            owner_layer="governance_runtime",
            purpose="Evidence-only reviewer audit receipt carrying ground-truth observations and audit outcomes.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/runtime/evidence_receipts.py",
            constants_module="dev.scripts.devctl.runtime.evidence_receipts",
            contract_id_attr="REVIEWER_AUDIT_RECEIPT_CONTRACT_ID",
            schema_version_attr="REVIEWER_AUDIT_RECEIPT_SCHEMA_VERSION",
            compatibility_window="additive fields only; audit receipts must remain readable by archive and review tooling.",
            migration_path="Add fields additively, update reviewer audit fixtures, then update evidence archive readers.",
            rollback_path="Keep prior audit receipt fields accepted until archived evidence can be retrieved by manifest ref.",
        ),
        ArtifactSchemaSpec(
            contract_id="RustAuditReport",
            owner_layer="governance_runtime",
            purpose="Machine-readable Rust audit aggregation emitted by the Rust audit report collector.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/rust_audit/report.py",
            constants_module="dev.scripts.devctl.runtime.audit_report_contracts",
            contract_id_attr="RUST_AUDIT_REPORT_CONTRACT_ID",
            schema_version_attr="RUST_AUDIT_REPORT_SCHEMA_VERSION",
            compatibility_window="additive fields only; audit reports must remain renderable as JSON and markdown.",
            migration_path="Add fields additively, then update Rust audit renderer/tests and platform contract rows before changing consumers.",
            rollback_path="Keep prior Rust audit report fields readable until renderer and report consumers are restored.",
        ),
        ArtifactSchemaSpec(
            contract_id="SecurityReport",
            owner_layer="governance_runtime",
            purpose="Machine-readable `devctl security` report emitted by the security command.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/commands/security.py",
            constants_module="dev.scripts.devctl.runtime.audit_report_contracts",
            contract_id_attr="SECURITY_REPORT_CONTRACT_ID",
            schema_version_attr="SECURITY_REPORT_SCHEMA_VERSION",
            compatibility_window="additive fields only; security report JSON and markdown must preserve typed header truth.",
            migration_path="Add fields additively, then update security command renderers/tests and platform contract rows before changing consumers.",
            rollback_path="Keep prior security report fields readable until command renderers and downstream consumers are restored.",
        ),
        ArtifactSchemaSpec(
            contract_id="ReviewTargets",
            owner_layer="governance_core",
            purpose="Portable review-target handoff artifact carrying summary, findings, and review packet.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/probe_report/artifacts.py",
            constants_module="dev.scripts.devctl.runtime.finding_contracts",
            contract_id_attr="REVIEW_TARGETS_CONTRACT_ID",
            schema_version_attr="REVIEW_TARGETS_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 P0/P1; additive changes only",
            migration_path="Keep handoff fields additive and update downstream importers before schema expansion.",
            rollback_path="Revert writer payload shape and constants together if downstream adoption regresses.",
        ),
        ArtifactSchemaSpec(
            contract_id="FileTopology",
            owner_layer="governance_core",
            purpose="Probe-topology artifact for hotspot and focused-graph analysis.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/probe_topology/builder.py",
            constants_module="dev.scripts.devctl.runtime.finding_contracts",
            contract_id_attr="PROBE_TOPOLOGY_CONTRACT_ID",
            schema_version_attr="PROBE_TOPOLOGY_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 P0/P1; additive changes only",
            migration_path="Expand topology payloads additively and update topology renderers/tests in the same slice.",
            rollback_path="Restore prior topology constants and emitters before removing consumer support.",
        ),
        ArtifactSchemaSpec(
            contract_id="DogfoodSelfCheckReceipt",
            owner_layer="governance_runtime",
            purpose="Evidence-only self-check receipt emitted by implementation agents for slice dogfood proof.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/runtime/evidence_receipts.py",
            constants_module="dev.scripts.devctl.runtime.evidence_receipts",
            contract_id_attr="DOGFOOD_SELF_CHECK_RECEIPT_CONTRACT_ID",
            schema_version_attr="DOGFOOD_SELF_CHECK_RECEIPT_SCHEMA_VERSION",
            compatibility_window="additive fields only; evidence receipts must remain readable by archive and review tooling.",
            migration_path="Add fields additively, update dogfood receipt fixtures, then update evidence archive readers.",
            rollback_path="Keep prior receipt fields accepted until archived evidence can be retrieved by manifest ref.",
        ),
        ArtifactSchemaSpec(
            contract_id="SessionActivityLog",
            owner_layer="governance_runtime",
            purpose=(
                "Per-session typed activity artifact summarizing what was added, "
                "verified, and archived from dogfood/audit receipts and packet evidence."
            ),
            schema_version=1,
            emitter_path="dev/scripts/devctl/runtime/session_activity_log.py",
            constants_module="dev.scripts.devctl.runtime.session_activity_log",
            contract_id_attr="SESSION_ACTIVITY_LOG_CONTRACT_ID",
            schema_version_attr="SESSION_ACTIVITY_LOG_SCHEMA_VERSION",
            compatibility_window="additive fields only; logs are session-scoped and archived by EvidenceArchive on close.",
            migration_path="Add fields additively, update session activity fixtures, then update archive readers and status renderers.",
            rollback_path="Keep prior log fields readable until archived session summaries can be retrieved by evidence archive ref.",
        ),
        ArtifactSchemaSpec(
            contract_id="CommitReceipt",
            owner_layer="governance_runtime",
            purpose=(
                "Governed-commit receipt artifact binding commit SHA, reviewer ack, "
                "audit synthesis, validation receipt, and remote pipeline lineage."
            ),
            schema_version=1,
            emitter_path="dev/scripts/devctl/runtime/commit_receipt.py",
            constants_module="dev.scripts.devctl.runtime.commit_receipt",
            contract_id_attr="COMMIT_RECEIPT_CONTRACT_ID",
            schema_version_attr="COMMIT_RECEIPT_SCHEMA_VERSION",
            compatibility_window="additive fields only; commit receipts must remain readable by publication and audit tooling.",
            migration_path="Add fields additively, update commit receipt fixtures, then update governed commit and publication readers.",
            rollback_path="Keep prior receipt fields readable until governed commit evidence can be retrieved by commit SHA.",
        ),
        ArtifactSchemaSpec(
            contract_id="GoalProgressReceipt",
            owner_layer="governance_runtime",
            purpose=(
                "Goal-progress receipt artifact tying goal_progress packets to a "
                "continuation_anchor and operator-visible progress percentage."
            ),
            schema_version=1,
            emitter_path="dev/scripts/devctl/runtime/goal_progress_receipt.py",
            constants_module="dev.scripts.devctl.runtime.goal_progress_receipt",
            contract_id_attr="GOAL_PROGRESS_RECEIPT_CONTRACT_ID",
            schema_version_attr="GOAL_PROGRESS_RECEIPT_SCHEMA_VERSION",
            compatibility_window="additive fields only; goal progress receipts must remain readable by develop and status surfaces.",
            migration_path="Add fields additively, update goal progress fixtures, then update develop/status readers.",
            rollback_path="Keep prior progress fields readable until continuation-anchor progress consumers are migrated.",
        ),
        ArtifactSchemaSpec(
            contract_id="ProbeAllowlist",
            owner_layer="repo_packs",
            purpose="Repo-root policy artifact for suppressed findings and routed design-decision packets.",
            schema_version=1,
            emitter_path="dev/scripts/checks/probe_report/decision_packets.py",
            constants_module="dev.scripts.devctl.runtime.finding_contracts",
            contract_id_attr="PROBE_ALLOWLIST_CONTRACT_ID",
            schema_version_attr="PROBE_ALLOWLIST_SCHEMA_VERSION",
            compatibility_window="stable for repo-local policy entries; additive entry fields only",
            migration_path="Add new allowlist fields additively and keep old matching semantics documented until migrated.",
            rollback_path="Preserve previous root payload shape and entry matching until repo policy is reverted.",
        ),
        ArtifactSchemaSpec(
            contract_id="QualityFeedbackSnapshot",
            owner_layer="governance_core",
            purpose="Maintainability scoring, false-positive analysis, and AI governance tuning recommendations.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/governance/quality_feedback/report_builder.py",
            constants_module="dev.scripts.devctl.governance.quality_feedback.models",
            contract_id_attr="QUALITY_FEEDBACK_CONTRACT_ID",
            schema_version_attr="QUALITY_FEEDBACK_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377; additive changes only",
            migration_path="Add new fields additively, then update renderers/tests before changing consumers.",
            rollback_path="Restore prior schema constants and report builder behavior before removing consumers.",
        ),
        ArtifactSchemaSpec(
            contract_id="ContextGraphSnapshot",
            owner_layer="governance_core",
            purpose="Versioned full-graph snapshot emitted by `devctl context-graph` for temporal diff/trend analysis.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/context_graph/snapshot.py",
            constants_module="dev.scripts.devctl.context_graph.snapshot",
            contract_id_attr="CONTEXT_GRAPH_SNAPSHOT_CONTRACT_ID",
            schema_version_attr="CONTEXT_GRAPH_SNAPSHOT_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 graph-routing rollout; additive changes only",
            migration_path="Add snapshot fields additively and update diff/trend readers before changing writers.",
            rollback_path="Restore prior snapshot constants and writer shape before removing consumers.",
        ),
        ArtifactSchemaSpec(
            contract_id="ContextGraphDelta",
            owner_layer="governance_core",
            purpose="Typed diff/trend payload between two saved `ContextGraphSnapshot` artifacts.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/context_graph/snapshot_diff.py",
            constants_module="dev.scripts.devctl.context_graph.snapshot_diff_models",
            contract_id_attr="CONTEXT_GRAPH_DELTA_CONTRACT_ID",
            schema_version_attr="CONTEXT_GRAPH_DELTA_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 temporal-graph rollout; additive changes only",
            migration_path="Keep delta fields additive and update markdown/JSON renderers plus CLI tests before schema expansion.",
            rollback_path="Restore prior delta constants and renderer/CLI shape before removing snapshot consumers.",
        ),
        ArtifactSchemaSpec(
            contract_id="SystemPicture",
            owner_layer="governance_core",
            purpose="Generated startup/runtime/evidence reducer snapshot emitted by `devctl system-picture`.",
            schema_version=1,
            emitter_path="dev/scripts/devctl/platform/system_picture.py",
            constants_module="dev.scripts.devctl.platform.system_picture_models",
            contract_id_attr="SYSTEM_PICTURE_CONTRACT_ID",
            schema_version_attr="SYSTEM_PICTURE_SCHEMA_VERSION",
            compatibility_window="best-effort stable within MP-377 system-picture rollout; additive changes only",
            migration_path="Keep reducer fields additive and update the CLI, ledger renderers, and proof consumers before schema expansion.",
            rollback_path="Restore prior reducer constants and renderers before removing existing system-picture consumers.",
        ),
    )
