"""Governed-exception policy, descriptor, and proof contract rows."""

from __future__ import annotations

from .contracts import ContractField, ContractSpec, CrossLinkSpec

GOVERNED_EXCEPTION_DESCRIPTOR_CONTRACTS: tuple[ContractSpec, ...] = (
    ContractSpec(
        contract_id="ExceptionPolicy",
        owner_layer="governance_runtime",
        purpose="Repo-pack exception policy projection used by validators.",
        required_fields=(
            ContractField("policy_id", "str", "Policy id."),
            ContractField("allowed_exception_classes", "tuple[str, ...]", "Allowed classes."),
            ContractField("forbidden_exception_classes", "tuple[str, ...]", "Forbidden classes."),
            ContractField("required_proof_by_action_kind", "Mapping[str, tuple[str, ...]] | None", "Proof by action kind."),
            ContractField("operator_approval_rules", "tuple[str, ...]", "Operator approval rules."),
            ContractField("stale_head_policy", "str", "Stale HEAD policy."),
            ContractField("dirty_worktree_policy", "str", "Dirty-worktree policy."),
            ContractField("remote_publish_policy", "str", "Remote publication proof policy."),
            ContractField("security_guard_policy", "str", "Security guard policy."),
        ),
        runtime_model="dev.scripts.devctl.runtime.governed_exception_contracts:ExceptionPolicy",
        startup_surface_tokens=("policy_id", "stale_head_policy", "remote_publish_policy"),
    ),
    ContractSpec(
        contract_id="ExceptionClass",
        owner_layer="governance_runtime",
        purpose="Policy-visible descriptor for one governed exception class.",
        required_fields=(
            ContractField("class_id", "str", "Exception class id."),
            ContractField("description", "str", "Class description."),
            ContractField("allowed_by_default", "bool", "Default allow flag."),
            ContractField("forbidden", "bool", "Forbidden-class flag."),
            ContractField("mutation_class", "bool", "Whether mutation evidence is required."),
            ContractField("action_kinds", "tuple[str, ...]", "Applicable action kinds."),
            ContractField("required_proof_refs", "tuple[str, ...]", "Required proof refs."),
        ),
        runtime_model="dev.scripts.devctl.runtime.governed_exception_contracts:ExceptionClass",
        startup_surface_tokens=("class_id", "forbidden", "mutation_class"),
    ),
    ContractSpec(
        contract_id="ExceptionLifecycleStatus",
        owner_layer="governance_runtime",
        purpose="Bounded status descriptor for governed exception lifecycles.",
        required_fields=(
            ContractField("status", "str", "Status id."),
            ContractField("terminal", "bool", "Whether the status is terminal."),
            ContractField("allowed_next_statuses", "tuple[str, ...]", "Allowed transitions."),
        ),
        runtime_model="dev.scripts.devctl.runtime.governed_exception_contracts:ExceptionLifecycleStatus",
        startup_surface_tokens=("status", "terminal"),
    ),
    ContractSpec(
        contract_id="ClosureProof",
        owner_layer="governance_runtime",
        purpose="Proof row that the original guarded command passed normally.",
        required_fields=(
            ContractField("closure_proof_id", "str", "Stable proof id."),
            ContractField("exception_lifecycle_id", "str", "Lifecycle proven by this row."),
            ContractField("normal_command", "str", "Original normal command."),
            ContractField("validation_receipt_id", "str", "ValidationReceipt id."),
            ContractField("action_result_id", "str", "ActionResult id."),
            ContractField("run_record_id", "str", "RunRecord id."),
            ContractField("exception_used", "bool", "Whether exception was used."),
            ContractField("remote_ref_verified", "bool", "Remote-ref proof flag."),
            ContractField("post_push_green", "bool", "Post-push proof flag."),
            ContractField("proof_artifacts", "tuple[str, ...]", "Proof artifact refs."),
        ),
        runtime_model="dev.scripts.devctl.runtime.governed_exception_contracts:ClosureProof",
        startup_surface_tokens=("closure_proof_id", "exception_used"),
        cross_links=(
            CrossLinkSpec(
                "exception_lifecycle_id",
                "GovernedExceptionLifecycle",
                "receipt_proves",
                target_resolver="governed_exception_lifecycle_id",
                required=True,
                validation_policy="must_resolve",
            ),
            CrossLinkSpec(
                "validation_receipt_id",
                "ValidationReceipt",
                "receipt_proves",
                target_resolver="validation_receipt_id",
                required=False,
                required_when="proof slice registers ValidationReceipt",
                validation_policy="deferred_until_validation_contract_registered",
            ),
            CrossLinkSpec(
                "action_result_id",
                "ActionResult",
                "receipt_proves",
                target_resolver="action_result_id",
                validation_policy="must_resolve_when_present",
            ),
            CrossLinkSpec(
                "run_record_id",
                "RunRecord",
                "related_to",
                target_resolver="run_record_id",
                validation_policy="must_resolve_when_present",
            ),
        ),
    ),
    ContractSpec(
        contract_id="AutoRepairReceipt",
        owner_layer="governance_runtime",
        purpose="Receipt for bounded safe auto-repair attempted before exception request.",
        required_fields=(
            ContractField("receipt_id", "str", "Stable auto-repair receipt id."),
            ContractField("action_kind", "str", "Guarded action kind."),
            ContractField("guard_id", "str", "Failed guard id."),
            ContractField("exception_class", "str", "Class repaired."),
            ContractField("repair_command", "str", "Bounded repair command."),
            ContractField("status", "str", "Repair status."),
            ContractField("rerun_guard_status", "str", "Guard status after repair."),
            ContractField("head", "str", "HEAD bound to repair evidence."),
            ContractField("created_at_utc", "str", "Receipt creation timestamp."),
            ContractField("evidence_refs", "tuple[str, ...]", "Evidence refs."),
        ),
        runtime_model="dev.scripts.devctl.runtime.governed_exception_contracts:AutoRepairReceipt",
        startup_surface_tokens=("receipt_id", "status", "guard_id"),
    ),
    ContractSpec(
        contract_id="ManualBypassImportReceipt",
        owner_layer="governance_runtime",
        purpose="Historical/manual bypass import evidence; not a blessed bypass path.",
        required_fields=(
            ContractField("receipt_id", "str", "Stable import receipt id."),
            ContractField("action_kind", "str", "Imported action kind."),
            ContractField("imported_command_summary", "str", "Sanitized manual command summary."),
            ContractField("operator_reason", "str", "Specific reason."),
            ContractField("head", "str", "HEAD observed for the import."),
            ContractField("finding_id", "str", "Linked FindingBacklog id."),
            ContractField("planned_finding_ingest_ref", "str", "Planned finding ingest hook."),
            ContractField("remote_ref_verified", "bool", "Remote-ref proof flag."),
            ContractField("post_push_proof_ref", "str", "Post-push proof ref."),
            ContractField("imported_at_utc", "str", "Import timestamp."),
            ContractField("evidence_refs", "tuple[str, ...]", "Evidence refs."),
        ),
        runtime_model="dev.scripts.devctl.runtime.governed_exception_contracts:ManualBypassImportReceipt",
        startup_surface_tokens=("receipt_id", "action_kind", "finding_id"),
        cross_links=(
            CrossLinkSpec(
                "finding_id",
                "FindingBacklog",
                "finding_blocks",
                target_node_kind="finding",
                target_resolver="finding_backlog_id",
                direction="reverse",
                required=True,
                required_when="no planned_finding_ingest_ref",
                validation_policy="must_resolve_or_planned_ingest",
            ),
            CrossLinkSpec(
                "planned_finding_ingest_ref",
                "PlatformFindingIngest",
                "related_to",
                target_node_kind="typed_contract",
                target_resolver="platform_finding_ingest_ref",
                required=True,
                required_when="no finding_id",
                validation_policy="must_resolve_or_finding",
            ),
        ),
    ),
)

__all__ = ["GOVERNED_EXCEPTION_DESCRIPTOR_CONTRACTS"]
