"""R98 packet-ingest contract proposals promoted to typed registry stubs."""

from __future__ import annotations

from ..runtime.governance_proposed_contracts import (
    AgentMindConsumptionReceipt,
    AgentWorkflowSpec,
    AssistantGuideMode,
    CharterDelivery,
    ComposesWith,
    ContinuousImprovementMode,
    ContractRef,
    FeatureLifecycleProof,
    GovernanceCompatibilityClaim,
    LifecycleReceipt,
    MandatoryIngestBeforeImplementInvariant,
    ModeChangeReceipt,
    PacketADRReceipt,
    PacketPlanIngestionMapping,
    PacketReadReceipt,
    PacketSupersessionLink,
    PacketUrgencyClassification,
    PlatformGuide,
    QueueBypassReasoning,
    RelationshipGraph,
    RoleCapability,
    RoleCapabilityRegistry,
    RuntimeErrorReceipt,
    SkillCompatibilityValidator,
    SkillLoadReceipt,
    SkillManifest,
    StalledQueueFinding,
    ToggleReceipt,
    TypedOutputHumanSummary,
    WorkflowStep,
)
from .contracts import ContractField, ContractSpec


def _fields(*names: str) -> tuple[ContractField, ...]:
    return tuple(
        ContractField(name, "object", "Promoted R98 packet-ingest contract field.")
        for name in names
    )


def _spec(model: type[object], *fields: str, purpose: str) -> ContractSpec:
    return ContractSpec(
        contract_id=model.__name__,
        owner_layer="governance_runtime",
        purpose=purpose,
        required_fields=_fields(*fields),
        runtime_model=f"{model.__module__}:{model.__name__}",
        startup_surface_tokens=fields[:3],
    )


GOVERNANCE_PROPOSED_STATE_CONTRACTS: tuple[ContractSpec, ...] = (
    _spec(
        LifecycleReceipt,
        "receipt_kind",
        "actor",
        "executed_at_utc",
        "evidence_ref",
        "proof_summary",
        purpose="One evidence receipt inside a FeatureLifecycleProof chain.",
    ),
    _spec(
        FeatureLifecycleProof,
        "feature_id",
        "commit_sha",
        "receipts",
        "completeness_score",
        "missing_receipt_kinds",
        purpose="Per-feature proof chain for build, test, dogfood, review, portability, and push evidence.",
    ),
    _spec(
        RoleCapability,
        "capability_id",
        "role_id",
        "command_refs",
        "authority_scope",
        "evidence_required",
        purpose="Composable role capability atom used to replace hard-coded role checks.",
    ),
    _spec(
        RoleCapabilityRegistry,
        "registry_id",
        "capabilities",
        "source_refs",
        "missing_capability_count",
        purpose="Registry of role capabilities available to typed agent workflows.",
    ),
    _spec(
        ToggleReceipt,
        "toggle_id",
        "mode_axis",
        "previous_state",
        "new_state",
        "actor",
        "changed_at_utc",
        "evidence_ref",
        "invariant_scope",
        purpose="Immutable evidence for user or system mode-toggle changes.",
    ),
    _spec(
        ModeChangeReceipt,
        "mode_axis",
        "previous_mode",
        "new_mode",
        "actor",
        "changed_at_utc",
        "evidence_ref",
        "gate_effect",
        purpose="Receipt for governance mode changes that may alter enforcement behavior.",
    ),
    _spec(
        AgentMindConsumptionReceipt,
        "consumer_actor",
        "provider_agent",
        "consumed_at_utc",
        "cursor",
        "event_count",
        "derived_actions",
        purpose="Evidence that an actor consumed peer agent-mind context before selecting work.",
    ),
    _spec(
        StalledQueueFinding,
        "finding_id",
        "row_id",
        "queued_since_utc",
        "age_days",
        "priority",
        "recommended_action",
        purpose="Derived finding for aged queued plan rows that require attention or bypass reasoning.",
    ),
    _spec(
        QueueBypassReasoning,
        "row_id",
        "bypass_reason",
        "actor",
        "decided_at_utc",
        "expires_at_utc",
        "evidence_ref",
        purpose="Typed rationale for consciously bypassing stalled queue work.",
    ),
    _spec(
        PacketReadReceipt,
        "packet_id",
        "reader_actor",
        "read_at_utc",
        "body_hash",
        "source_ref",
        purpose="Evidence that an actor opened the packet body instead of inferring from projections.",
    ),
    _spec(
        PacketUrgencyClassification,
        "packet_id",
        "urgency",
        "classified_at_utc",
        "classifier_actor",
        "rationale",
        purpose="Typed packet urgency classification for priority and preemption.",
    ),
    _spec(
        PacketSupersessionLink,
        "packet_id",
        "supersedes_packet_ids",
        "superseded_by_packet_id",
        "rationale",
        purpose="Typed supersession relationship between related review packets.",
    ),
    _spec(
        RelationshipGraph,
        "graph_id",
        "node_refs",
        "edge_refs",
        "generated_at_utc",
        "source_refs",
        purpose="Packet, plan-row, contract, and evidence relationship graph.",
    ),
    _spec(
        PacketADRReceipt,
        "packet_id",
        "decision_id",
        "precedent_packet_ids",
        "status",
        "rationale",
        purpose="ADR-style packet decision receipt with precedent packet links.",
    ),
    _spec(
        CharterDelivery,
        "charter_id",
        "contract_ids",
        "delivered_at_utc",
        "evidence_refs",
        purpose="Delivery proof for packet-charter contract clusters.",
    ),
    _spec(
        WorkflowStep,
        "capability_id",
        "execution_order",
        "requires_agent_mind_signal",
        "produces_typed_evidence_kinds",
        purpose="One ordered capability step inside an agent workflow.",
    ),
    _spec(
        AgentWorkflowSpec,
        "workflow_id",
        "target_role_id",
        "command_sequence",
        "coordination_with",
        "user_customization_points",
        purpose="Role-bound typed workflow over commands, capabilities, and coordination signals.",
    ),
    _spec(
        ContinuousImprovementMode,
        "mode_id",
        "enabled",
        "scan_commands",
        "promotion_rules",
        "evidence_refs",
        purpose="Mode that continuously runs architecture-finding probes and emits typed findings.",
    ),
    _spec(
        RuntimeErrorReceipt,
        "error_id",
        "error_class",
        "source_path",
        "occurred_at_utc",
        "finding_ref",
        "traceback_ref",
        purpose="Bridge from code-path errors into durable findings and governed exception evidence.",
    ),
    _spec(
        TypedOutputHumanSummary,
        "output_ref",
        "human_summary",
        "ok",
        "risk",
        "generated_at_utc",
        purpose="Human-readable summary required on typed command output.",
    ),
    _spec(
        ContractRef,
        "contract_id_ref",
        "schema_version_ref",
        "owner_path",
        "relation",
        purpose="Reusable typed reference to another contract family.",
    ),
    _spec(
        ComposesWith,
        "source_contract_id",
        "target_contract_id",
        "composition_kind",
        "compatibility_rule",
        "evidence_ref",
        purpose="Universal composition primitive for contract compatibility edges.",
    ),
    _spec(
        AssistantGuideMode,
        "mode_id",
        "enabled",
        "guide_surface_refs",
        "context_resolver_ref",
        "evidence_ref",
        purpose="Assistant guide mode for contextual help while users operate the governance system.",
    ),
    _spec(
        PlatformGuide,
        "guide_id",
        "source_contract_refs",
        "generated_at_utc",
        "surface_refs",
        "freshness_ref",
        purpose="Auto-updating user-facing platform guide projected from typed authority.",
    ),
    _spec(
        GovernanceCompatibilityClaim,
        "invariant_id",
        "claim_status",
        "evidence_ref",
        purpose="One declared compatibility claim for a loaded skill or extension.",
    ),
    _spec(
        SkillManifest,
        "skill_id",
        "skill_name",
        "source",
        "version",
        "declared_capabilities",
        "declared_governance_compatibility",
        "skill_entry_point",
        "validation_status",
        purpose="Registered skill metadata plus declared governance compatibility.",
    ),
    _spec(
        SkillLoadReceipt,
        "skill_id",
        "load_outcome",
        "governance_check_findings",
        "actor",
        "loaded_at_utc",
        "expiry_at_utc",
        purpose="Evidence for loading or rejecting a skill under governance compatibility checks.",
    ),
    _spec(
        SkillCompatibilityValidator,
        "validator_id",
        "skill_id",
        "invariant_refs",
        "verdict",
        "findings",
        purpose="Validator result for whether a skill can compose with governance invariants.",
    ),
    _spec(
        MandatoryIngestBeforeImplementInvariant,
        "invariant_id",
        "required_mapping_store",
        "enforcement_surface",
        "toggle_scope",
        "severity_policy",
        purpose="Class-25 invariant requiring typed packet-to-plan ingestion before implementation work.",
    ),
    _spec(
        PacketPlanIngestionMapping,
        "packet_id",
        "plan_row_id",
        "mapped_at_utc",
        "actor",
        "source_hash",
        purpose="Typed mapping from a packet body to an actionable plan row.",
    ),
)
