"""Generated SYSTEM_MAP managed-block renderer."""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
from typing import Any

from ..common_io import display_path
from ..config import REPO_ROOT
from .connectivity_registry import build_connectivity_registry_snapshot
from .system_map_models import (
    SystemMapRootSummary,
    SystemMapSnapshot,
    SystemMapSurfaceSummary,
)

GENERATED_BLOCK_BEGIN = "<!-- BEGIN DEVCTL_SYSTEM_MAP_GENERATED -->"
GENERATED_BLOCK_END = "<!-- END DEVCTL_SYSTEM_MAP_GENERATED -->"
GENERATED_BLOCK_ANCHOR = "## 0. Living Flowchart"
TRACKED_ARCHITECTURE_ROOTS = (
    "dev/scripts/devctl",
    "dev/scripts/checks",
)
REQUIRED_COMMANDS = (
    "python3 dev/scripts/devctl.py system-map --format md",
    "python3 dev/scripts/devctl.py render-surfaces --write --surface system_map_index --format md",
    "python3 dev/scripts/checks/check_instruction_surface_sync.py --format md",
)


def build_system_map_snapshot(
    *,
    repo_root: Path = REPO_ROOT,
    policy_path: str | Path | None = None,
) -> SystemMapSnapshot:
    """Build the bounded typed snapshot rendered into SYSTEM_MAP.md."""
    resolved_policy_path = _resolve_policy_path(repo_root=repo_root, policy_path=policy_path)
    policy, warnings = _load_policy(resolved_policy_path)
    governed_surfaces = _surface_summaries(policy)
    registry = build_connectivity_registry_snapshot(
        repo_root=repo_root,
        governed_surface_ids=tuple(surface.surface_id for surface in governed_surfaces),
    )
    return SystemMapSnapshot(
        schema_version=1,
        contract_id="SystemMapSnapshot",
        generated_section_id="devctl_system_map_generated",
        tracked_roots=tuple(
            _summarize_architecture_root(repo_root=repo_root, root=root)
            for root in TRACKED_ARCHITECTURE_ROOTS
        ),
        governed_surfaces=governed_surfaces,
        connectivity_registry=registry,
        required_commands=REQUIRED_COMMANDS,
        source_policy_path=display_path(resolved_policy_path, repo_root=repo_root),
        warnings=tuple(warnings) + registry.warnings,
    )


def render_system_map_markdown(snapshot: SystemMapSnapshot) -> str:
    """Render the generated block body for human review."""
    lines: list[str] = []
    lines.append("## Generated Connectivity Snapshot")
    lines.append("")
    lines.append(
        "This block is generated by `system_map_renderer`; edit the typed inputs "
        "or rerun the renderer instead of hand-editing this block."
    )
    lines.append("")
    lines.append(f"- contract_id: `{snapshot.contract_id}`")
    lines.append(f"- section_id: `{snapshot.generated_section_id}`")
    lines.append(f"- source_policy: `{snapshot.source_policy_path}`")
    lines.append("")
    lines.append("### Architecture Roots")
    lines.append("")
    lines.append("| Root | Python files | Largest namespaces |")
    lines.append("|---|---:|---|")
    for root in snapshot.tracked_roots:
        namespace_summary = ", ".join(
            f"{name}={count}" for name, count in root.top_level_counts[:8]
        )
        lines.append(
            f"| `{root.root}` | {root.python_file_count} | {namespace_summary or 'none'} |"
        )
    lines.append("")
    lines.append("### Governed Surfaces")
    lines.append("")
    lines.append("| Surface | Renderer | Output | Scope |")
    lines.append("|---|---|---|---|")
    for surface in snapshot.governed_surfaces:
        scope = "local-only" if surface.local_only else "tracked" if surface.tracked else "untracked"
        lines.append(
            f"| `{surface.surface_id}` | `{surface.renderer}` | `{surface.output_path}` | {scope} |"
        )
    registry = snapshot.connectivity_registry
    lines.append("")
    lines.append("### Typed Connectivity Registry")
    lines.append("")
    lines.append(f"- contract_id: `{registry.contract_id}`")
    lines.append(f"- source_contract_count: {registry.source_contract_count}")
    lines.append(f"- connected_contract_count: {len(registry.connected_contracts)}")
    lines.append("")
    lines.append("| Contract | Owner | Fields | Writer | Consumers |")
    lines.append("|---|---|---:|---|---|")
    for contract in registry.connected_contracts[:12]:
        consumers = ", ".join(contract.projection_ids[:5]) or "none"
        lines.append(
            f"| `{contract.contract_id}` | `{contract.owner_layer}` | "
            f"{len(contract.fields)} | `{contract.writer.writer_id}` | {consumers} |"
        )
    lines.append("")
    lines.append("### Required Commands")
    lines.append("")
    for command in snapshot.required_commands:
        lines.append(f"- `{command}`")
    if snapshot.warnings:
        lines.append("")
        lines.append("### Warnings")
        lines.append("")
        for warning in snapshot.warnings:
            lines.append(f"- {warning}")
    return "\n".join(lines)


def render_system_map_document(
    current_text: str,
    snapshot: SystemMapSnapshot,
) -> str:
    """Return SYSTEM_MAP.md text with the generated block inserted or replaced."""
    managed_block = (
        f"{GENERATED_BLOCK_BEGIN}\n"
        f"{render_system_map_markdown(snapshot)}\n"
        f"{GENERATED_BLOCK_END}"
    )
    begin_index = current_text.find(GENERATED_BLOCK_BEGIN)
    end_index = current_text.find(GENERATED_BLOCK_END)
    if begin_index != -1 and end_index != -1 and end_index > begin_index:
        replacement_end = end_index + len(GENERATED_BLOCK_END)
        return current_text[:begin_index] + managed_block + current_text[replacement_end:]

    anchor_index = current_text.find(GENERATED_BLOCK_ANCHOR)
    if anchor_index == -1:
        prefix = current_text.rstrip()
        return (prefix + "\n\n" if prefix else "") + managed_block + "\n"
    return (
        current_text[:anchor_index].rstrip()
        + "\n\n"
        + managed_block
        + "\n\n"
        + current_text[anchor_index:].lstrip()
    )


def _resolve_policy_path(
    *,
    repo_root: Path,
    policy_path: str | Path | None,
) -> Path:
    if policy_path is not None:
        candidate = Path(policy_path)
        return candidate if candidate.is_absolute() else repo_root / candidate
    return repo_root / "dev/config/devctl_repo_policy.json"


def _load_policy(policy_path: Path) -> tuple[dict[str, Any], list[str]]:
    try:
        payload = json.loads(policy_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {}, [f"unable to read repo policy: {exc}"]
    if not isinstance(payload, dict):
        return {}, ["repo policy root is not an object"]
    return payload, []


def _surface_summaries(policy: dict[str, Any]) -> tuple[SystemMapSurfaceSummary, ...]:
    repo_governance = policy.get("repo_governance")
    if not isinstance(repo_governance, dict):
        return ()
    surface_generation = repo_governance.get("surface_generation")
    if not isinstance(surface_generation, dict):
        return ()
    surfaces = surface_generation.get("surfaces")
    if not isinstance(surfaces, list):
        return ()
    rows: list[SystemMapSurfaceSummary] = []
    for entry in surfaces:
        if not isinstance(entry, dict):
            continue
        surface_id = str(entry.get("id") or "").strip()
        renderer = str(entry.get("renderer") or "").strip()
        output_path = str(entry.get("output_path") or "").strip()
        if not surface_id or not renderer or not output_path:
            continue
        rows.append(
            SystemMapSurfaceSummary(
                surface_id=surface_id,
                renderer=renderer,
                output_path=output_path,
                tracked=bool(entry.get("tracked", False)),
                local_only=bool(entry.get("local_only", False)),
            )
        )
    return tuple(rows)


def _summarize_architecture_root(
    *,
    repo_root: Path,
    root: str,
) -> SystemMapRootSummary:
    root_path = repo_root / root
    files = _python_files(root_path)
    buckets: Counter[str] = Counter()
    for path in files:
        rel_parts = path.relative_to(root_path).parts
        bucket = rel_parts[0] if len(rel_parts) > 1 else "(root)"
        buckets[bucket] += 1
    top_level_counts = tuple(
        sorted(buckets.items(), key=lambda item: (-item[1], item[0]))
    )
    return SystemMapRootSummary(
        root=root,
        python_file_count=len(files),
        top_level_counts=top_level_counts,
    )


def _python_files(root_path: Path) -> tuple[Path, ...]:
    if not root_path.exists():
        return ()
    return tuple(
        sorted(
            path
            for path in root_path.rglob("*.py")
            if "__pycache__" not in path.parts
        )
    )
