"""Markdown renderers for system-picture artifacts and proof-ledger projections."""

from __future__ import annotations

from .system_picture_models import SystemPictureSection, SystemPictureSnapshot


def render_system_picture_markdown(snapshot: SystemPictureSnapshot) -> str:
    """Render the bounded system-picture artifact for repo-owned consumers."""
    lines = ["# devctl system-picture", ""]
    lines.append(f"- snapshot_id: {snapshot.snapshot_id}")
    lines.append(f"- generated_at_utc: {snapshot.generated_at_utc}")
    lines.append(f"- repo_name: {snapshot.repo_name}")
    lines.append(f"- current_branch: {snapshot.current_branch or '(unknown)'}")
    lines.append(f"- head_commit_sha: {snapshot.head_commit_sha or '(unknown)'}")
    lines.append(f"- tree_hash: {snapshot.tree_hash or '(unknown)'}")
    lines.append(f"- current_section_count: {snapshot.current_section_count}")
    lines.append(f"- stale_section_count: {snapshot.stale_section_count}")
    lines.append(f"- missing_section_count: {snapshot.missing_section_count}")
    lines.append("")
    lines.append("## Sections")
    lines.append("")
    lines.append("| Section | Status | Source Path | Source Command |")
    lines.append("|---|---|---|---|")
    for section in snapshot.sections:
        lines.append(
            "| {title} | {status} | `{source_path}` | `{source_command}` |".format(
                title=section.title,
                status=section.status,
                source_path=section.source_path or "-",
                source_command=section.source_command or "-",
            )
        )
    lines.append("")
    for section in snapshot.sections:
        lines.extend(_render_section_detail(section))
    return "\n".join(lines)


def render_system_picture_ledger_markdown(snapshot: SystemPictureSnapshot) -> str:
    """Render the tracked proof-ledger projection from the current snapshot."""
    date = _snapshot_date(snapshot)
    startup = _section(snapshot, "startup")
    graph = _section(snapshot, "graph")
    review_runtime = _section(snapshot, "review_runtime")
    governance_review = _section(snapshot, "governance_review")
    external_findings = _section(snapshot, "external_findings")
    data_science = _section(snapshot, "data_science")

    startup_summary = startup.summary if startup is not None else {}
    graph_summary = graph.summary if graph is not None else {}
    review_summary = review_runtime.summary if review_runtime is not None else {}
    governance_summary = governance_review.summary if governance_review is not None else {}
    external_summary = external_findings.summary if external_findings is not None else {}
    data_science_summary = data_science.summary if data_science is not None else {}

    lines = [
        "<!-- Generated by `python3 dev/scripts/devctl.py system-picture --write-ledger --format md`; edit `dev/scripts/devctl/platform/system_picture_render.py` instead of hand-editing this file. -->",
        "",
        "# AI Governance Platform Proof Ledger",
        "",
        f"**Status**: active reference  |  **Last updated**: {date} | **Owner:** Tooling/control plane/product architecture",
        "",
        "Reference-only proof and differentiation ledger for the `MP-377` AI governance",
        "platform work.",
        "",
        "This file is generated from the repo-owned `devctl system-picture` reducer.",
        "It is not execution authority. Canonical execution state remains in:",
        "",
        "- `dev/active/MASTER_PLAN.md`",
        "- `dev/active/ai_governance_platform.md`",
        "- `dev/active/platform_authority_loop.md`",
        "- `dev/active/portable_code_governance.md`",
        "",
        "## Upkeep Contract",
        "",
        "Refresh this ledger through the repo-owned command whenever proof claims,",
        "artifact owners, or cross-repo evidence materially change:",
        "",
        "```bash",
        "python3 dev/scripts/devctl.py system-picture --format md",
        "python3 dev/scripts/devctl.py system-picture --write-ledger --format md",
        "```",
        "",
        "Keep the underlying machine truth in the typed/runtime artifacts and managed",
        "reports. Keep accepted execution decisions in the owner plans, not here.",
        "",
        "## Current Claim Boundary",
        "",
        "What is honestly proved now:",
        "",
        "- a self-hosting repo-local governance runtime exists in code",
        "- startup, work intake, review state, and governed commit/push use typed",
        "  contracts and machine-readable projections",
        "- fail-closed startup/review/checkpoint behavior is live, not just planned",
        "- the platform already has real cross-repo pilot evidence for `probe-report`",
        "  and routed `check` adoption scans",
        "",
        "What is not honestly proved yet:",
        "",
        "- full extracted product closure",
        "- broad any-repo startup/push portability",
        "- completion of the authority-loop closure",
        "- a finished market moat around raw coding-agent primitives",
        "",
        "## Claim Matrix",
        "",
        "| Claim | Status | Evidence anchors | Next gate |",
        "|---|---|---|---|",
        "| Self-hosting repo-local AI governance runtime exists in code today | proved | `dev/scripts/devctl/runtime/project_governance_contract.py`, `dev/scripts/devctl/runtime/startup_context.py`, `dev/scripts/devctl/runtime/work_intake.py`, `dev/scripts/devctl/runtime/review_state_models.py` | keep the typed/runtime surfaces green under `MP-377` |",
        "| Startup, review, and governed commit/push use typed contracts instead of prompt-only policy | proved | `dev/scripts/devctl/runtime/startup_context.py`, `dev/scripts/devctl/runtime/reviewer_runtime_models.py`, `dev/scripts/devctl/runtime/action_contracts.py`, `dev/scripts/devctl/runtime/remote_commit_pipeline_models.py` | finish the remaining authority-loop closure tracked in `dev/active/platform_authority_loop.md` |",
        "| Fail-closed startup/review/checkpoint behavior is live, not just planned | proved | `python3 dev/scripts/devctl.py startup-context --format summary`, `python3 dev/scripts/devctl.py review-channel --action doctor --terminal none --format json`, `dev/reports/review_channel/latest/review_state.json` | keep the fail-closed receipts stable as bridge/projection authority narrows |",
        "| Cross-repo adoption proof exists for guard/probe/adoption-scan paths | proved but scoped | `dev/reports/audits/2026-03-14-portable-governance-pilot-rerun.md`, `dev/reports/audits/portable_governance_pilot_2026-03-14.json`, `dev/reports/governance/external_pilot_findings.jsonl`, `dev/active/portable_code_governance.md` | extend the proof from adoption-scan surfaces into stronger startup/push portability |",
        "| External auditors using GitHub-connected review flows or ChatGPT-style repo review can audit the system from tracked docs and evidence surfaces | supported now | this ledger, `dev/guides/AI_GOVERNANCE_PLATFORM.md`, `dev/guides/PORTABLE_CODE_GOVERNANCE.md`, `dev/audits/2026-03-24-chatgpt-integration-intake.md` | keep routing accepted external findings into owner plans instead of leaving them as standalone audit prose |",
        "| Broad any-repo startup/push portability is complete | not proved | `dev/active/platform_authority_loop.md`, `dev/active/portable_code_governance.md` | close repo-pack / Step-0 / push-authority portability gaps |",
        "",
        "## Current Proof Snapshot",
        "",
        f"Baseline observed from the generated `system-picture` snapshot `{snapshot.snapshot_id}` on {date}:",
        "",
        "| Signal | Current evidence |",
        "|---|---|",
        f"| Branch | `{snapshot.current_branch or '(unknown)'}` |",
        "| Bootstrap graph | "
        f"`{graph_summary.get('node_count', 'n/a')}` source files, "
        f"`{graph_summary.get('guard_count', 'n/a')}` guards, "
        f"`{graph_summary.get('probe_count', 'n/a')}` probes, "
        f"`{graph_summary.get('plan_count', 'n/a')}` active plans, "
        f"`{graph_summary.get('edge_count', 'n/a')}` edges |",
        "| Startup authority | "
        f"`action={startup_summary.get('advisory_action', 'unknown')}`,"
        f" `reason={startup_summary.get('advisory_reason', 'unknown')}`,"
        f" `startup_authority_ok={startup_summary.get('startup_authority_ok', False)}`,"
        f" `ahead_of_upstream_commits={startup_summary.get('ahead_of_upstream_commits', 'n/a')}` |",
        "| Review runtime | "
        f"`attention.status={review_summary.get('attention_status', 'unknown')}`,"
        f" `reviewer_freshness={review_summary.get('reviewer_freshness', 'unknown')}`,"
        f" `review_needed={review_summary.get('review_needed', 'n/a')}`,"
        f" `review_accepted={review_summary.get('review_accepted', 'n/a')}` |",
        "| Governance review | "
        f"`total_findings={governance_summary.get('total_findings', 'n/a')}`,"
        f" `open_finding_count={governance_summary.get('open_finding_count', 'n/a')}`,"
        f" `fixed_count={governance_summary.get('fixed_count', 'n/a')}`,"
        f" `cleanup_rate_pct={governance_summary.get('cleanup_rate_pct', 'n/a')}` |",
        "| Cross-repo imported findings | "
        f"`unique_repo_count={external_summary.get('unique_repo_count', 'n/a')}`,"
        f" `total_findings={external_summary.get('total_findings', 'n/a')}`,"
        f" `reviewed_count={external_summary.get('reviewed_count', 'n/a')}`,"
        f" `adjudication_coverage_pct={external_summary.get('adjudication_coverage_pct', 'n/a')}` |",
        "| Command/watchdog telemetry | "
        f"`total_events={data_science_summary.get('total_events', 'n/a')}`,"
        f" `command_success_rate_pct={data_science_summary.get('command_success_rate_pct', 'n/a')}`,"
        f" `watchdog_total_episodes={data_science_summary.get('watchdog_total_episodes', 'n/a')}`,"
        f" `watchdog_success_rate_pct={data_science_summary.get('watchdog_success_rate_pct', 'n/a')}` |",
        "",
        "This matters because the current repo state is being reduced from typed",
        "startup/review/evidence artifacts rather than hand-maintained prose.",
        "",
        "## Repo-Backed POC Evidence",
        "",
        "### 1. Typed governance and startup authority",
        "",
        "- `dev/scripts/devctl/runtime/project_governance_contract.py`",
        "- `dev/scripts/devctl/runtime/startup_context.py`",
        "- `dev/scripts/devctl/runtime/work_intake_models.py`",
        "- `dev/scripts/devctl/runtime/work_intake.py`",
        "- `dev/scripts/devctl/tests/runtime/test_project_governance.py`",
        "- `dev/scripts/devctl/tests/runtime/test_startup_context.py`",
        "- `dev/scripts/devctl/tests/runtime/test_work_intake.py`",
        "",
        "### 2. Typed review/runtime state",
        "",
        "- `dev/scripts/devctl/runtime/review_state_models.py`",
        "- `dev/scripts/devctl/runtime/reviewer_runtime_models.py`",
        "- `dev/scripts/devctl/runtime/review_state_parser.py`",
        "- `dev/reports/review_channel/latest/review_state.json`",
        "- `dev/reports/review_channel/latest/commit_pipeline.json`",
        "- `dev/reports/review_channel/latest/compact.json`",
        "- `dev/reports/review_channel/latest/full.json`",
        "",
        "### 3. Governed commit/push execution",
        "",
        "- `dev/scripts/devctl/runtime/action_contracts.py`",
        "- `dev/scripts/devctl/runtime/remote_commit_pipeline_models.py`",
        "- `dev/scripts/devctl/commands/vcs/governed_executor.py`",
        "- `dev/scripts/devctl/tests/vcs/test_governed_executor.py`",
        "",
        "### 4. Multi-surface backend direction",
        "",
        "- `dev/active/ai_governance_platform.md`",
        "- `dev/guides/AI_GOVERNANCE_PLATFORM.md`",
        "- `app/operator_console/README.md`",
        "- `app/operator_console/views/main_window.py`",
        "",
        "## Cross-Repo Adoption Evidence",
        "",
        "Primary evidence:",
        "",
        "- `dev/reports/audits/2026-03-14-portable-governance-pilot-rerun.md`",
        "- `dev/reports/audits/portable_governance_pilot_2026-03-14.json`",
        "- `dev/reports/governance/external_pilot_findings.jsonl`",
        "- `dev/reports/governance/external_findings_latest/external_findings_summary.json`",
        "- `dev/reports/data_science/latest/summary.json`",
        "- `dev/active/portable_code_governance.md`",
        "",
        "Current honest limitation:",
        "",
        "- startup/push proof is still incomplete for arbitrary repos because",
        "  `startup-context` does not yet provide the fully target-local Step-0 proof",
        "  path from the engine checkout alone",
        "",
        "## External Audit Consumers",
        "",
        "Use this ledger as the first maintained handoff surface for:",
        "",
        "- GitHub-side reviewers who need one tracked place to verify what is already",
        "  proved versus still open",
        "- ChatGPT Pro or other repo-connected external reviewers who can read the repo",
        "  but should not invent their own authority hierarchy",
        "- internal/external developers auditing whether the platform really improves",
        "  code quality across repos",
        "",
        "Recommended read order:",
        "",
        "- `dev/guides/AI_GOVERNANCE_PLATFORM.md`",
        "- `dev/active/platform_authority_loop.md`",
        "- `dev/active/portable_code_governance.md`",
        "- `dev/audits/2026-03-24-chatgpt-integration-intake.md`",
        "- `dev/integrations/EXTERNAL_REPOS.md`",
        "",
        "## Evidence Map",
        "",
        "### Canonical machine ledgers",
        "",
        "| Surface | Path | Why it matters |",
        "|---|---|---|",
        "| command telemetry | `dev/reports/audits/devctl_events.jsonl` | proves what commands ran, when, and with what success/failure shape |",
        "| governance adjudication | `dev/reports/governance/finding_reviews.jsonl` | proves reviewed findings, cleanup rate, false-positive rate, and systemic absorption |",
        "| external adoption findings | `dev/reports/governance/external_pilot_findings.jsonl` | preserves imported cross-repo findings instead of relying on narrative summaries |",
        "| system-picture history | `dev/reports/system_picture/history/snapshots.jsonl` | preserves the generated external-review/system-picture snapshots over time |",
        "",
        "### Canonical human projections over those ledgers",
        "",
        "| Surface | Path | Why it matters |",
        "|---|---|---|",
        "| governance review summary | `dev/reports/governance/latest/review_summary.md` | current scoreboard for findings fixed, open, deferred, and by-check cleanup |",
        "| external findings summary | `dev/reports/governance/external_findings_latest/external_findings_summary.md` | current cross-repo imported-finding coverage and reviewed status |",
        "| data science summary | `dev/reports/data_science/latest/summary.md` | current telemetry rollup, watchdog metrics, and external-finding corpus counts |",
        "| probe summary | `dev/reports/probes/latest/summary.md` | current review-probe risk picture for the active tree |",
        "| system-picture summary | `dev/reports/system_picture/latest/summary.md` | current generated startup/runtime/evidence reducer for repo-owned consumers |",
        "| system-picture ledger preview | `dev/reports/system_picture/latest/proof_ledger.md` | generated GitHub-visible proof projection before tracked-doc writeback |",
        "",
        "## Market Review",
        "",
        f"As of {date}, the raw primitives are no longer unique:",
        "",
        "- OpenAI Codex now markets coding-agent execution, parallel work, built-in",
        "  worktrees, AGENTS.md guidance, and verifiable evidence surfaces",
        "- Claude Code documents read/edit/run behavior, hooks, subagents, multiple",
        "  surfaces, and parallel work",
        "- Continue covers agent workflows across Mission Control, terminal, and CI/CD",
        "- Aider covers terminal pair programming, repo maps, git integration, and",
        "  lint/test repair loops",
        "",
        "What is still differentiated here is the composition:",
        "",
        "- repo-owned typed authority instead of prompt-only policy",
        "- bounded startup and work-intake packets instead of unrestricted repo",
        "  recrawling as startup authority",
        "- explicit reviewer/implementer/operator separation with typed runtime state",
        "- fail-closed checkpoint/push gating",
        "- packetized approval and review receipts",
        "- a documented plan to keep all frontends on one backend instead of letting",
        "  each surface invent its own control plane",
        "",
        "## Proof Log",
        "",
        f"- {date}: Generated `system-picture` snapshot `{snapshot.snapshot_id}` for",
        "  the current tree and refreshed the tracked proof ledger projection through",
        "  `python3 dev/scripts/devctl.py system-picture --write-ledger --format md`.",
        f"- {date}: Current graph reducer source is `{graph.source_path if graph is not None else 'n/a'}`.",
        f"- {date}: Current startup source is `{startup.source_path if startup is not None else 'n/a'}`.",
        f"- {date}: Current review-runtime source is `{review_runtime.source_path if review_runtime is not None else 'n/a'}`.",
        "- 2026-03-24 to 2026-03-25: External ChatGPT architecture review was captured",
        "  in `dev/audits/2026-03-24-chatgpt-integration-intake.md`, reswept against",
        "  the live codebase, and split into \"already exists\" versus genuine gaps with",
        "  tracked owner-plan routing.",
        "- 2026-03-14: Corrected portable-governance pilot rerun established the current",
        "  cross-repo proof baseline in",
        "  `dev/reports/audits/2026-03-14-portable-governance-pilot-rerun.md` and",
        "  `dev/reports/audits/portable_governance_pilot_2026-03-14.json`.",
        "",
        "## Canonical Claim Language",
        "",
        "- \"This repo already proves a self-hosting POC of a repo-local AI governance",
        "  runtime.\"",
        "- \"The unusual part is not the raw coding-agent primitive. It is the typed",
        "  governance/control-plane shape assembled around it.\"",
        "- \"The system treats AI as the implementation/search layer, not the authority",
        "  layer.\"",
        "- \"Cross-repo proof exists for adoption-scan guard/probe paths, but broad",
        "  startup/push portability is still an explicit open gate.\"",
        "",
        "Do not claim:",
        "",
        "- \"Nobody else has built anything similar.\"",
        "- \"The full extracted product is already proved.\"",
        "- \"Any-repo startup/push portability is complete.\"",
        "",
        "## Current Proof Commands",
        "",
        "```bash",
        "python3 dev/scripts/devctl.py system-picture --format md",
        "python3 dev/scripts/devctl.py system-picture --format json",
        "python3 dev/scripts/devctl.py system-picture --write-ledger --format md",
        "python3 dev/scripts/devctl.py startup-context --format summary",
        "python3 dev/scripts/devctl.py context-graph --mode bootstrap --format md",
        "python3 dev/scripts/devctl.py governance-review --format md",
        "python3 dev/scripts/devctl.py data-science --format md",
        "python3 dev/scripts/devctl.py probe-report --format md",
        "```",
        "",
        "For cross-repo proof, keep using the policy/adoption surfaces documented in",
        "`dev/scripts/README.md`, especially:",
        "",
        "```bash",
        "python3 dev/scripts/devctl.py governance-bootstrap --target-repo /tmp/copied-repo --format md",
        "python3 dev/scripts/devctl.py check --profile ci --repo-path /tmp/copied-repo --adoption-scan --format md",
        "python3 dev/scripts/devctl.py probe-report --repo-path /tmp/copied-repo --adoption-scan --format md",
        "```",
        "",
        "## Ongoing Append Rule",
        "",
        "When new proof lands, refresh `system-picture`, keep the generated",
        "`history/snapshots.jsonl` chain intact, and add the owner-plan progress",
        "note in the same change so the evidence stays machine-backed and",
        "repo-visible.",
        "",
        "Each proof update should keep these pieces aligned:",
        "",
        "- the generated `dev/reports/system_picture/latest/summary.{json,md}`",
        "- the tracked projection at `dev/audits/AI_GOVERNANCE_PLATFORM_PROOF_LEDGER.md`",
        "- the owner-plan progress/audit notes in `dev/active/ai_governance_platform.md`",
        "- the owner-plan progress/audit notes in `dev/active/platform_authority_loop.md`",
        "",
        "Prefer appending evidence through typed artifacts, commands, receipts,",
        "tests, and plan-log updates. Do not turn this file back into a hand-kept",
        "second authority source.",
    ]
    return "\n".join(lines) + "\n"


def _render_section_detail(section: SystemPictureSection) -> list[str]:
    lines = [f"## {section.title}", ""]
    lines.append(f"- section_id: {section.section_id}")
    lines.append(f"- status: {section.status}")
    lines.append(f"- source_path: {section.source_path or '(none)'}")
    lines.append(f"- source_command: {section.source_command or '(none)'}")
    lines.append(f"- generated_at_utc: {section.generated_at_utc or '(unknown)'}")
    lines.append(f"- section_hash: {section.section_hash}")
    if section.notes:
        lines.append("- notes:")
        for note in section.notes:
            lines.append(f"  - {note}")
    lines.append("")
    lines.append("### Summary")
    lines.append("")
    for key, value in section.summary.items():
        lines.append(f"- {key}: `{value}`")
    if not section.summary:
        lines.append("- none")
    lines.append("")
    return lines


def _section(
    snapshot: SystemPictureSnapshot,
    section_id: str,
) -> SystemPictureSection | None:
    for section in snapshot.sections:
        if section.section_id == section_id:
            return section
    return None


def _snapshot_date(snapshot: SystemPictureSnapshot) -> str:
    generated = snapshot.generated_at_utc.strip()
    return generated.split("T", 1)[0] if "T" in generated else generated or "unknown"
