"""Rendering helpers for `devctl triage-loop` outputs."""

from __future__ import annotations

from datetime import datetime
from typing import Any


def render_attempt_lines(attempts: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    if not attempts:
        lines.append("- none")
        return lines
    for row in attempts:
        lines.append(
            "- "
            + f"#{row.get('attempt')} "
            + f"run_id={row.get('run_id')} "
            + f"sha={row.get('run_sha')} "
            + f"conclusion={row.get('run_conclusion')} "
            + f"backlog={row.get('backlog_count')} "
            + f"status={row.get('status')}"
        )
        run_url = str(row.get("run_url") or "").strip()
        if run_url:
            lines.append(f"  url: {run_url}")
        message = str(row.get("message") or "").strip()
        if message:
            lines.append(f"  note: {message}")
    return lines


def render_markdown(report: dict) -> str:
    lines = ["# devctl triage-loop", ""]
    lines.append(f"- ok: {report.get('ok')}")
    lines.append(f"- mode: {report.get('mode')}")
    lines.append(f"- notify: {report.get('notify')}")
    lines.append(f"- repo: {report.get('repo')}")
    lines.append(f"- branch: {report.get('branch')}")
    lines.append(f"- workflow: {report.get('workflow')}")
    lines.append(f"- max_attempts: {report.get('max_attempts')}")
    lines.append(f"- completed_attempts: {report.get('completed_attempts')}")
    lines.append(f"- unresolved_count: {report.get('unresolved_count')}")
    lines.append(f"- source_event: {report.get('source_event')}")
    lines.append(f"- source_run_id: {report.get('source_run_id')}")
    lines.append(f"- source_run_sha: {report.get('source_run_sha')}")
    lines.append(f"- source_correlation: {report.get('source_correlation')}")
    lines.append(f"- reason: {report.get('reason')}")
    notify_result = report.get("notify_result")
    if isinstance(notify_result, dict):
        lines.append(f"- notify_result_ok: {notify_result.get('ok')}")
        lines.append(
            "- notify_target: "
            + f"{notify_result.get('target_kind') or 'n/a'}:{notify_result.get('target_id') or 'n/a'}"
        )
        if notify_result.get("comment_url"):
            lines.append(f"- notify_comment_url: {notify_result.get('comment_url')}")
        if notify_result.get("error"):
            lines.append(f"- notify_error: {notify_result.get('error')}")
    lines.append("")
    lines.append("## Attempts")
    lines.append("")
    lines.extend(render_attempt_lines(report.get("attempts", [])))
    warnings = report.get("warnings", [])
    if isinstance(warnings, list) and warnings:
        lines.append("")
        lines.append("## Warnings")
        lines.append("")
        lines.extend(f"- {warning}" for warning in warnings)
    bundle = report.get("bundle", {})
    if isinstance(bundle, dict) and bundle:
        lines.append("")
        lines.append("## Bundle")
        lines.append("")
        for key in ("markdown", "json", "mp_proposal"):
            value = bundle.get(key)
            if value:
                lines.append(f"- {key}: {value}")
    return "\n".join(lines)


def build_master_plan_proposal(report: dict) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    unresolved = int(report.get("unresolved_count") or 0)
    attempts = report.get("attempts", [])
    lines = [
        "# MASTER_PLAN Proposal (Auto-generated by devctl triage-loop)",
        "",
        f"- generated_utc: {now}",
        f"- branch: {report.get('branch')}",
        f"- workflow: {report.get('workflow')}",
        f"- mode: {report.get('mode')}",
        f"- unresolved_medium_high: {unresolved}",
        f"- completed_attempts: {report.get('completed_attempts')}",
        f"- reason: {report.get('reason')}",
        "",
        "## Suggested MASTER_PLAN update",
        "",
    ]
    if unresolved == 0:
        lines.extend(
            [
                "1. Mark the current CodeRabbit medium/high remediation slice as complete.",
                "2. Link the latest Ralph loop artifact URL under MP-306 evidence notes.",
                "3. Keep follow-up checks focused on CI lanes that were red in the source run.",
            ]
        )
    else:
        lines.extend(
            [
                "1. Keep the CodeRabbit remediation slice in-progress.",
                "2. Add/refresh a checklist item capturing unresolved medium/high findings.",
                "3. Attach latest Ralph artifact URLs and open owner-routed follow-up tasks.",
            ]
        )
    lines.append("")
    lines.append("## Attempt trace")
    lines.append("")
    lines.extend(render_attempt_lines(attempts))
    lines.append("")
    lines.append("## Guardrails")
    lines.append("")
    lines.append("- Proposal only: this artifact does not edit `dev/active/MASTER_PLAN.md`.")
    lines.append("- A reviewer/automation stage should validate check bundles before applying changes.")
    return "\n".join(lines)
