"""Default receipt-store classifications used by the consumer guard."""

from __future__ import annotations

from .models import ReceiptStoreClassification


DEFAULT_CLASSIFICATIONS: tuple[ReceiptStoreClassification, ...] = (
    ReceiptStoreClassification(
        store_path="dev/state/plan_index.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.master_plan_store:upsert_plan_row_jsonl",),
        reader_refs=("dev.scripts.devctl.runtime.master_plan_store:read_plan_rows_jsonl",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/plan_source_snapshots.jsonl",
        writer_refs=(
            "dev.scripts.devctl.runtime.plan_source_retention_store:write_plan_source_snapshots_jsonl",
            "dev.scripts.devctl.runtime.plan_source_retention_store:upsert_plan_source_snapshots",
        ),
        reader_refs=(
            "dev.scripts.devctl.runtime.plan_source_retention_store:read_plan_source_snapshots",
            "dev.scripts.checks.check_no_ingestion_churn_without_advancement",
        ),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/plan_ingestion_receipts.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.plan_intent_ingestion:append_plan_intent_ingestion_receipt",),
        reader_refs=(
            "dev.scripts.devctl.commands.development.plan_intake_render",
            "dev.scripts.checks.feature_has_proof_receipt.command",
        ),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/plan_row_closure_receipts.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.commit_to_plan_row_reducer:append_plan_row_closure_receipt",),
        reader_refs=(
            "dev.scripts.devctl.runtime.commit_to_plan_row_reducer:load_plan_row_closure_receipts",
            "dev.scripts.checks.check_slice_finishes_or_reverts",
            "dev.scripts.checks.check_plan_row_must_advance",
        ),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/governed_exception_lifecycles.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.raw_git_bypass_receipts",),
        reader_refs=("dev.scripts.devctl.runtime.governed_exception_store:load_governed_exception_lifecycles",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/bypass_lifecycles.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.bypass_lifecycle_registry",),
        reader_refs=("dev.scripts.devctl.runtime.bypass_lifecycle_registry:active_bypass_lifecycles",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/artifact_receipts.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.artifact_receipt_ledger",),
        reader_refs=("dev.scripts.devctl.runtime.artifact_receipt_ledger:iter_artifact_receipts",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/baseline_authority_inventories.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.baseline_authority_inventory:append_baseline_authority_inventory_receipt",),
        reader_refs=("dev.scripts.devctl.runtime.baseline_authority_inventory:read_baseline_authority_inventory_receipts",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/contract_registry.jsonl",
        writer_refs=("dev.scripts.devctl.platform.contract_registry:write_contract_registry_rows",),
        reader_refs=(
            "dev.scripts.devctl.platform.contract_registry:read_contract_registry_rows",
            "dev.scripts.checks.platform_contract_closure.contract_registry_closure",
            "dev.scripts.checks.systemmap_covers_contract_registry.command",
        ),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/governance_reconciliation_receipts.jsonl",
        writer_refs=(),
        reader_refs=(),
        disposition="pending_runtime_contract",
    ),
    ReceiptStoreClassification(
        store_path="dev/state/ground_truth_probe_receipts.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.ground_truth_probe_receipt:append_ground_truth_probe_receipt",),
        reader_refs=(
            "dev.scripts.devctl.runtime.ground_truth_probe_receipt:latest_ground_truth_probe_receipt",
            "dev.scripts.devctl.runtime.ground_truth_probe_gate:evaluate_ground_truth_probe_receipt",
            "dev.scripts.checks.ground_truth_probe_gate.command",
        ),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/topology_hardcode_inventory.jsonl",
        writer_refs=("dev.scripts.checks.topology_hardcode.command:write_report",),
        reader_refs=("dev.scripts.checks.topology_hardcode.command:_load_inventory",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/non_trivial_output_proof_remediation_findings.jsonl",
        writer_refs=("dev.scripts.checks.non_trivial_output_proof.command:write_remediation_ledger",),
        reader_refs=("dev.scripts.checks.non_trivial_output_proof.command:_ledgered_finding_ids",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/role_review_completed_remediation_findings.jsonl",
        writer_refs=("dev.scripts.checks.role_review_completed.command:write_remediation_ledger",),
        reader_refs=("dev.scripts.checks.role_review_completed.command:_ledgered_finding_ids",),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/transition_modules.jsonl",
        writer_refs=("dev/scripts/README.md:managed manifest",),
        reader_refs=(
            "dev.scripts.devctl.runtime.governed_transitions:load_transition_module_rows",
            "dev.scripts.checks.governed_transitions.command",
        ),
    ),
    ReceiptStoreClassification(
        store_path="dev/state/raw_git_bypass_receipts.jsonl",
        writer_refs=("dev.scripts.devctl.runtime.raw_git_bypass_receipts",),
        reader_refs=("dev.scripts.devctl.runtime.raw_git_bypass_receipts",),
    ),
    ReceiptStoreClassification(
        store_path="dev/reports/feature_proof_receipts",
        writer_refs=("dev.scripts.devctl.runtime.feature_proof_receipt:write_feature_proof_receipt_artifact",),
        reader_refs=(
            "dev.scripts.devctl.runtime.feature_proof_receipt:feature_proof_receipt_from_mapping",
            "dev.scripts.checks.check_receipt_schema_validation",
            "dev.scripts.checks.feature_has_proof_receipt.command",
        ),
    ),
)
