"""Shared packet-kind constants for agent collaboration workflows."""

from __future__ import annotations

TASK_STARTED_PACKET_KIND = "task_started"
TASK_PROGRESS_PACKET_KIND = "task_progress"
TASK_PRODUCED_PACKET_KIND = "task_produced"
TASK_BLOCKED_PACKET_KIND = "task_blocked"
REVIEW_STARTED_PACKET_KIND = "review_started"
REVIEW_FAILED_PACKET_KIND = "review_failed"
REVIEW_ACCEPTED_PACKET_KIND = "review_accepted"
OPERATOR_ROUTED_PACKET_KIND = "operator_routed"

COLLABORATION_LIFECYCLE_PACKET_KINDS = frozenset(
    {
        TASK_STARTED_PACKET_KIND,
        TASK_PROGRESS_PACKET_KIND,
        TASK_PRODUCED_PACKET_KIND,
        TASK_BLOCKED_PACKET_KIND,
        REVIEW_STARTED_PACKET_KIND,
        REVIEW_FAILED_PACKET_KIND,
        REVIEW_ACCEPTED_PACKET_KIND,
        OPERATOR_ROUTED_PACKET_KIND,
    }
)

__all__ = [
    "COLLABORATION_LIFECYCLE_PACKET_KINDS",
    "OPERATOR_ROUTED_PACKET_KIND",
    "REVIEW_ACCEPTED_PACKET_KIND",
    "REVIEW_FAILED_PACKET_KIND",
    "REVIEW_STARTED_PACKET_KIND",
    "TASK_BLOCKED_PACKET_KIND",
    "TASK_PRODUCED_PACKET_KIND",
    "TASK_PROGRESS_PACKET_KIND",
    "TASK_STARTED_PACKET_KIND",
]
