"""Contract constants for evidence-only receipt artifacts."""

from __future__ import annotations

DOGFOOD_SELF_CHECK_RECEIPT_CONTRACT_ID = "DogfoodSelfCheckReceipt"
DOGFOOD_SELF_CHECK_RECEIPT_SCHEMA_VERSION = 1
REVIEWER_AUDIT_RECEIPT_CONTRACT_ID = "ReviewerAuditReceipt"
REVIEWER_AUDIT_RECEIPT_SCHEMA_VERSION = 1

__all__ = [
    "DOGFOOD_SELF_CHECK_RECEIPT_CONTRACT_ID",
    "DOGFOOD_SELF_CHECK_RECEIPT_SCHEMA_VERSION",
    "REVIEWER_AUDIT_RECEIPT_CONTRACT_ID",
    "REVIEWER_AUDIT_RECEIPT_SCHEMA_VERSION",
]
