"""Public ProjectGovernance contract surface.

This module stays as the stable import path while the startup-authority
contract is split into dedicated contract and parsing modules.
"""

from __future__ import annotations

from .project_governance_contract import (
    PROJECT_GOVERNANCE_CONTRACT_ID,
    PROJECT_GOVERNANCE_SCHEMA_VERSION,
    ArtifactRoots,
    BridgeConfig,
    BundleOverrides,
    DocBudget,
    DocPolicy,
    DocRegistry,
    DocRegistryEntry,
    EnabledChecks,
    MemoryRoots,
    PathRoots,
    PlanRegistry,
    PlanRegistryEntry,
    PlanRegistryRoots,
    ProjectGovernance,
    RepoIdentity,
    RepoPackRef,
)
from .project_governance_push import PushEnforcement
from .project_governance_parse import (
    artifact_roots_from_mapping,
    bridge_config_from_mapping,
    bundle_overrides_from_mapping,
    doc_budget_from_mapping,
    doc_policy_from_mapping,
    doc_registry_entry_from_mapping,
    doc_registry_from_mapping,
    enabled_checks_from_mapping,
    memory_roots_from_mapping,
    path_roots_from_mapping,
    plan_registry_entry_from_mapping,
    plan_registry_from_mapping,
    plan_registry_roots_from_mapping,
    project_governance_from_mapping,
    repo_identity_from_mapping,
    repo_pack_ref_from_mapping,
)

__all__ = [
    "PROJECT_GOVERNANCE_CONTRACT_ID",
    "PROJECT_GOVERNANCE_SCHEMA_VERSION",
    "ArtifactRoots",
    "BridgeConfig",
    "BundleOverrides",
    "DocBudget",
    "DocPolicy",
    "DocRegistry",
    "DocRegistryEntry",
    "EnabledChecks",
    "MemoryRoots",
    "PathRoots",
    "PlanRegistry",
    "PlanRegistryEntry",
    "PlanRegistryRoots",
    "ProjectGovernance",
    "PushEnforcement",
    "RepoIdentity",
    "RepoPackRef",
    "artifact_roots_from_mapping",
    "bridge_config_from_mapping",
    "bundle_overrides_from_mapping",
    "doc_budget_from_mapping",
    "doc_policy_from_mapping",
    "doc_registry_entry_from_mapping",
    "doc_registry_from_mapping",
    "enabled_checks_from_mapping",
    "memory_roots_from_mapping",
    "path_roots_from_mapping",
    "plan_registry_entry_from_mapping",
    "plan_registry_from_mapping",
    "plan_registry_roots_from_mapping",
    "project_governance_from_mapping",
    "repo_identity_from_mapping",
    "repo_pack_ref_from_mapping",
]
