"""Inactivity-watchdog bash template for review-channel conductor scripts.

Extracted from ``launch_script.py`` to keep that module under the Python
soft file-size limit (350 lines).

Operator-authorized 2026-04-24 (path 1 fix): codex CLI sometimes idles
after `task_complete` instead of exiting, so the supervision
``while true`` loop in `_supervision_loop_lines` never relaunches. The
watchdog generated by `inactivity_watchdog_lines` tails the latest
`~/.codex/sessions/<date>/rollout-*.jsonl` mtime and SIGINTs the
conductor when no new event has landed for the configured timeout
window, allowing the existing supervision loop to relaunch.
"""

from __future__ import annotations


def inactivity_watchdog_lines(provider: str) -> list[str]:
    """Generate the inactivity-watchdog bash function (provider-agnostic).

    Spawned alongside the conductor agent. Polls the latest rollout JSONL
    file under ``REVIEW_CHANNEL_CODEX_SESSIONS_ROOT`` (today + yesterday
    UTC, since a session can cross midnight) and SIGINTs the conductor
    when no rollout activity has happened for
    ``REVIEW_CHANNEL_INACTIVITY_TIMEOUT_SECONDS``. Honors
    ``REVIEW_CHANNEL_WATCHDOG_STARTUP_GRACE_SECONDS`` so a slow-starting
    conductor isn't reaped before its first task. The supervision
    ``while true`` loop in ``_supervision_loop_lines`` then sees a
    non-zero exit and relaunches per the existing restart policy.
    """
    label = f"[review-channel] {provider} inactivity-watchdog"
    return [
        "review_channel_latest_rollout_mtime() {",
        '  local sessions_root="$REVIEW_CHANNEL_CODEX_SESSIONS_ROOT"',
        '  local today yesterday',
        '  today="$(date -u +%Y/%m/%d)"',
        '  yesterday="$(date -u -v-1d +%Y/%m/%d 2>/dev/null || date -u -d "yesterday" +%Y/%m/%d 2>/dev/null || echo "")"',
        '  local latest=0',
        '  local candidate stamp dir',
        '  for dir in "$sessions_root/$today" "$sessions_root/$yesterday"; do',
        '    [[ -z "$dir" || ! -d "$dir" ]] && continue',
        "    candidate=\"$(ls -t \"$dir\"/rollout-*.jsonl 2>/dev/null | head -1)\"",
        '    [[ -z "$candidate" ]] && continue',
        '    stamp="$(stat -f %m "$candidate" 2>/dev/null || stat -c %Y "$candidate" 2>/dev/null || echo 0)"',
        '    if [[ "$stamp" =~ ^[0-9]+$ ]] && (( stamp > latest )); then',
        '      latest=$stamp',
        '    fi',
        '  done',
        '  printf "%s\\n" "$latest"',
        "}",
        "",
        "review_channel_inactivity_watchdog() {",
        '  local target_pid="$1"',
        '  local timeout_seconds="$2"',
        '  local startup_grace="$3"',
        '  local poll_seconds="$4"',
        '  local started_at last_seen now age',
        '  started_at=$(date -u +%s)',
        '  last_seen=0',
        '  while kill -0 "$target_pid" 2>/dev/null; do',
        '    sleep "$poll_seconds"',
        '    now=$(date -u +%s)',
        '    if (( now - started_at < startup_grace )); then',
        '      continue',
        '    fi',
        '    last_seen=$(review_channel_latest_rollout_mtime)',
        '    if (( last_seen == 0 )); then',
        '      last_seen=$started_at',
        '    fi',
        '    age=$(( now - last_seen ))',
        '    if (( age > timeout_seconds )); then',
        f'      printf "%s\\n" "{label}: idle ${{age}}s > ${{timeout_seconds}}s; sending SIGINT to PID $target_pid (latest rollout mtime $last_seen, now $now)" >&2',
        '      kill -INT "$target_pid" 2>/dev/null || true',
        '      sleep 5',
        '      kill -KILL "$target_pid" 2>/dev/null || true',
        '      return 0',
        '    fi',
        '  done',
        "}",
        "",
    ]
