"""Launch-authority bash template for review-channel conductor scripts.

Extracted from ``launch_script.py`` to keep that module under the Python
soft file-size limit (350 lines).

Owns the embedded Python heredoc that validates HEAD/instruction/session
freshness before each conductor turn (``review_channel_launch_authority_check``)
plus the small companion helper
``review_channel_exit_is_non_restartable``. Both are pure text-template
generators with no Python-runtime side effects.
"""

from __future__ import annotations

from .launch_authority import NON_RESTARTABLE_LAUNCH_AUTHORITY_EXIT_CODE


def launch_authority_check_lines() -> list[str]:
    return [
        "review_channel_launch_authority_check() {",
        "  python3 - \"$REVIEW_CHANNEL_REVIEW_STATE_PATH\" \"$REVIEW_CHANNEL_PREPARED_HEAD_SHA\" \"$REVIEW_CHANNEL_PREPARED_INSTRUCTION_REVISION\" \"$REVIEW_CHANNEL_PREPARED_SESSION_TOKEN\" <<'PY_AUTHORITY'",
        "import hashlib",
        "import json",
        "import subprocess",
        "import sys",
        "",
        f"EXIT_CODE = {NON_RESTARTABLE_LAUNCH_AUTHORITY_EXIT_CODE}",
        "review_state_path, expected_head, expected_revision, expected_token = sys.argv[1:5]",
        "",
        "def fail(message):",
        "    print(f\"[review-channel] launch authority stale: {message}\", file=sys.stderr)",
        "    raise SystemExit(EXIT_CODE)",
        "",
        "def text(value):",
        "    return str(value or \"\").strip()",
        "",
        "def mapping(value):",
        "    return value if isinstance(value, dict) else {}",
        "",
        "def normalize_session_id(value):",
        "    text = str(value or \"\").strip()",
        "    if text.lower() in {\"local-review\", \"markdown-bridge\", \"review-channel\"}:",
        "        return \"review-channel\"",
        "    return text",
        "",
        "if not any((expected_head, expected_revision, expected_token)):",
        "    raise SystemExit(0)",
        "",
        "try:",
        "    live_head = subprocess.run(",
        "        [\"git\", \"rev-parse\", \"HEAD\"],",
        "        capture_output=True,",
        "        text=True,",
        "        timeout=5,",
        "        check=False,",
        "    )",
        "except Exception as exc:",
        "    fail(f\"could not read git HEAD: {exc}\")",
        "if live_head.returncode != 0:",
        "    fail(\"could not read git HEAD\")",
        "current_head = live_head.stdout.strip()",
        "if expected_head and current_head != expected_head:",
        "    fail(f\"prepared_head_sha={expected_head} current_head_sha={current_head}\")",
        "",
        "if not review_state_path:",
        "    fail(\"review_state_path missing\")",
        "try:",
        "    with open(review_state_path, \"r\", encoding=\"utf-8\") as handle:",
        "        review_state = json.load(handle)",
        "except Exception as exc:",
        "    fail(f\"could not read typed review state {review_state_path}: {exc}\")",
        "review = mapping(review_state.get(\"review\"))",
        "bridge = mapping(review_state.get(\"bridge\"))",
        "current_session = mapping(review_state.get(\"current_session\"))",
        "current_revision = text(",
        "    current_session.get(\"current_instruction_revision\")",
        "    or bridge.get(\"current_instruction_revision\")",
        ")",
        "if expected_revision and current_revision != expected_revision:",
        "    fail(",
        "        f\"prepared_instruction_revision={expected_revision} \"",
        "        f\"current_instruction_revision={current_revision}\"",
        "    )",
        "session_id = normalize_session_id(review.get(\"session_id\") or \"markdown-bridge\")",
        "last_poll = text(bridge.get(\"last_codex_poll_utc\"))",
        "token_payload = \"\\0\".join(",
        "    part for part in (session_id, current_revision, last_poll) if part",
        ")",
        "current_token = (",
        "    hashlib.sha256(token_payload.encode(\"utf-8\")).hexdigest()[:16]",
        "    if token_payload",
        "    else \"\"",
        ")",
        "if expected_token and current_token != expected_token:",
        "    fail(f\"prepared_session_token={expected_token} current_session_token={current_token}\")",
        "raise SystemExit(0)",
        "PY_AUTHORITY",
        "}",
        "",
        "review_channel_exit_is_non_restartable() {",
        "  local exit_code=\"$1\"",
        "  local code",
        "  for code in ${=REVIEW_CHANNEL_NON_RESTARTABLE_EXIT_CODES}; do",
        "    if [[ \"$exit_code\" == \"$code\" ]]; then",
        "      return 0",
        "    fi",
        "  done",
        "  return 1",
        "}",
        "",
    ]
