"""Parser builders for docs, status, and reporting devctl commands."""

from __future__ import annotations

import argparse

from ..common import add_standard_output_arguments


def add_docs_check_parser(sub: argparse._SubParsersAction) -> None:
    """Register the `docs-check` parser."""
    docs_cmd = sub.add_parser("docs-check", help="Verify user-facing docs are updated")
    docs_cmd.add_argument("--user-facing", action="store_true", help="Enforce user-facing doc updates")
    docs_cmd.add_argument("--strict", action="store_true", help="Require all user docs when --user-facing")
    docs_cmd.add_argument(
        "--strict-tooling",
        action="store_true",
        help="Require all canonical maintainer docs for tooling/release changes",
    )
    docs_cmd.add_argument(
        "--since-ref",
        help="Use commit-range mode by comparing changes from this ref (e.g. origin/develop, HEAD~1)",
    )
    docs_cmd.add_argument(
        "--head-ref",
        default="HEAD",
        help="Range-mode head ref used with --since-ref (default: HEAD)",
    )
    docs_cmd.add_argument(
        "--quality-policy",
        help=(
            "Optional repo policy JSON file used to resolve repo-governance docs rules "
            "(defaults to dev/config/devctl_repo_policy.json or DEVCTL_QUALITY_POLICY)."
        ),
    )
    add_standard_output_arguments(docs_cmd)


def add_status_parser(
    sub: argparse._SubParsersAction,
    *,
    default_ci_limit: int,
) -> None:
    """Register the `status` parser."""
    status_cmd = sub.add_parser("status", help="Summarize git + mutation status")
    status_cmd.add_argument("--ci", action="store_true", help="Include recent GitHub runs")
    status_cmd.add_argument("--ci-limit", type=int, default=default_ci_limit)
    status_cmd.add_argument(
        "--require-ci",
        action="store_true",
        help="Exit non-zero when CI fetch fails (implies --ci)",
    )
    status_cmd.add_argument(
        "--dev-logs",
        action="store_true",
        help="Include guarded Dev Mode JSONL session summary",
    )
    status_cmd.add_argument(
        "--dev-root",
        help="Override dev-log root (default: $HOME/.voiceterm/dev)",
    )
    status_cmd.add_argument(
        "--dev-sessions-limit",
        type=int,
        default=5,
        help="Maximum recent session files to scan when --dev-logs",
    )
    status_cmd.add_argument(
        "--no-parallel",
        action="store_true",
        help="Run collection probes sequentially instead of in parallel",
    )
    status_cmd.add_argument(
        "--probe-report",
        action="store_true",
        help="Include aggregated review-probe summary for the current worktree",
    )
    status_cmd.add_argument(
        "--quality-policy",
        help=(
            "Optional repo policy JSON file used by --probe-report "
            "(defaults to dev/config/devctl_repo_policy.json or "
            "DEVCTL_QUALITY_POLICY)."
        ),
    )
    add_standard_output_arguments(
        status_cmd,
        format_choices=("json", "md", "text"),
        default_format="text",
    )


def add_report_parser(
    sub: argparse._SubParsersAction,
    *,
    default_ci_limit: int,
) -> None:
    """Register the `report` parser."""
    report_cmd = sub.add_parser("report", help="Generate a JSON/MD report")
    report_cmd.add_argument("--ci", action="store_true", help="Include recent GitHub runs")
    report_cmd.add_argument("--ci-limit", type=int, default=default_ci_limit)
    report_cmd.add_argument(
        "--dev-logs",
        action="store_true",
        help="Include guarded Dev Mode JSONL session summary",
    )
    report_cmd.add_argument(
        "--dev-root",
        help="Override dev-log root (default: $HOME/.voiceterm/dev)",
    )
    report_cmd.add_argument(
        "--dev-sessions-limit",
        type=int,
        default=5,
        help="Maximum recent session files to scan when --dev-logs",
    )
    report_cmd.add_argument(
        "--pedantic",
        action="store_true",
        help="Include advisory clippy::pedantic artifact summary if available",
    )
    report_cmd.add_argument(
        "--pedantic-refresh",
        action="store_true",
        help="Refresh pedantic artifacts before rendering the report",
    )
    report_cmd.add_argument(
        "--pedantic-summary-json",
        help="Override summary JSON path generated by `check --profile pedantic`",
    )
    report_cmd.add_argument(
        "--pedantic-lints-json",
        help="Override lint histogram JSON path generated by `check --profile pedantic`",
    )
    report_cmd.add_argument(
        "--pedantic-policy-file",
        help="Override pedantic lint policy file",
    )
    report_cmd.add_argument(
        "--rust-audits",
        action="store_true",
        help="Include Rust guard audit summary in the report",
    )
    report_cmd.add_argument(
        "--rust-audit-mode",
        choices=["auto", "absolute", "working-tree", "commit-range"],
        default="auto",
        help="Rust audit scan mode (default: absolute unless --since-ref is provided)",
    )
    report_cmd.add_argument(
        "--since-ref",
        help="Base ref used when --rust-audit-mode commit-range",
    )
    report_cmd.add_argument(
        "--head-ref",
        default="HEAD",
        help="Head ref used with --since-ref for Rust audit commit-range mode",
    )
    report_cmd.add_argument(
        "--with-charts",
        action="store_true",
        help="Generate matplotlib charts for the Rust audit section when enabled",
    )
    report_cmd.add_argument(
        "--chart-dir",
        help="Optional chart output directory for Rust audit charts",
    )
    report_cmd.add_argument(
        "--emit-bundle",
        action="store_true",
        help="Write report markdown/json bundle files",
    )
    report_cmd.add_argument(
        "--bundle-dir",
        default="dev/reports/report",
        help="Directory used when --emit-bundle writes report artifacts",
    )
    report_cmd.add_argument(
        "--bundle-prefix",
        default="devctl-report",
        help="Filename prefix used when --emit-bundle writes report artifacts",
    )
    report_cmd.add_argument(
        "--quality-backlog",
        action="store_true",
        help="Include prioritized cross-language quality backlog summary (md + json friendly)",
    )
    report_cmd.add_argument(
        "--quality-backlog-top-n",
        type=int,
        default=40,
        help="Maximum ranked backlog paths to include when --quality-backlog",
    )
    report_cmd.add_argument(
        "--quality-backlog-include-tests",
        action="store_true",
        help="Include test files in quality backlog ranking",
    )
    report_cmd.add_argument(
        "--python-guard-backlog",
        action="store_true",
        help="Include Python guard hotspot aggregation (dict schema, globals, params, nesting, god-class)",
    )
    report_cmd.add_argument(
        "--python-guard-backlog-top-n",
        type=int,
        default=20,
        help="Maximum ranked Python guard hotspots to include when --python-guard-backlog",
    )
    report_cmd.add_argument(
        "--probe-report",
        action="store_true",
        help="Include aggregated review-probe summary (uses --since-ref/--head-ref when provided)",
    )
    report_cmd.add_argument(
        "--quality-policy",
        help=(
            "Optional repo policy JSON file used by --probe-report "
            "(defaults to dev/config/devctl_repo_policy.json or "
            "DEVCTL_QUALITY_POLICY)."
        ),
    )
    report_cmd.add_argument(
        "--no-parallel",
        action="store_true",
        help="Run collection probes sequentially instead of in parallel",
    )
    add_standard_output_arguments(report_cmd)


def add_docs_and_reporting_parsers(
    sub: argparse._SubParsersAction,
    *,
    default_ci_limit: int,
) -> None:
    """Register docs, status, and report parser definitions."""
    add_docs_check_parser(sub)
    add_status_parser(sub, default_ci_limit=default_ci_limit)
    add_report_parser(sub, default_ci_limit=default_ci_limit)
