"""Renderer for generated AI instruction boot cards."""

from __future__ import annotations

from dataclasses import dataclass


INSTRUCTION_BOOT_CARD_CONTRACT_ID = "InstructionBootCard"
INSTRUCTION_BOOT_CARD_SCHEMA_VERSION = 1

REQUIRED_BOOT_SECTIONS = (
    "This is projection-only",
    "Run in order",
    "Typed authority",
    "Projection-only surfaces",
    "Never",
    "Focused navigation",
    "Active-plan onboarding (adding files under `dev/active/`)",
    "Verification before handoff",
)

REQUIRED_BOOT_COMMANDS = (
    "session --role",
    "startup-context",
    "session-resume",
    "review-channel status",
    "context-graph --mode bootstrap",
    "develop next",
    "system-map",
    "system-picture",
    "platform-contracts",
    "render-surfaces",
    "docs-check",
    "test-python",
)

FORBIDDEN_BOOT_CLAIMS = (
    "AGENTS.md is canonical authority",
    "CLAUDE.md is canonical authority",
    "VoiceTerm is hidden default platform authority",
)


@dataclass(frozen=True, slots=True)
class InstructionBootCard:
    """One generated bootstrap card for an AI-facing instruction surface."""

    surface_id: str
    output_path: str
    role_arg: str
    actor_arg: str
    source_path: str
    repo_pack_id: str
    repo_pack_version: str


def build_instruction_boot_card(
    *,
    surface_id: str,
    output_path: str,
    source_path: str,
    repo_pack_id: str,
    repo_pack_version: str,
) -> str:
    """Render a short projection-only bootstrap card."""
    role_arg, actor_arg = _surface_role(surface_id=surface_id, output_path=output_path)
    card = InstructionBootCard(
        surface_id=surface_id,
        output_path=output_path,
        role_arg=role_arg,
        actor_arg=actor_arg,
        source_path=source_path,
        repo_pack_id=repo_pack_id,
        repo_pack_version=repo_pack_version,
    )
    lines = [
        "# Agent Boot Card",
        "",
        "<!-- Generated by `python3 dev/scripts/devctl.py render-surfaces --write --format md`; do not edit by hand. -->",
        "",
        "## This is projection-only",
        "",
        f"- `{card.output_path}` is a generated boot card, not durable policy authority.",
        "- Durable process authority lives in typed state, active owner docs, repo-pack policy, contracts, receipts, and guards.",
        "- VoiceTerm is this repo's first-party adopter/client of the portable governance platform.",
        "- Resolve repo behavior through `ProjectGovernance`, repo-pack policy, and typed runtime contracts.",
        "",
        "## Run in order",
        "",
        f"1. `python3 dev/scripts/devctl.py session --role {card.role_arg} --include-review-status always --format json`",
        "   Use `SessionOrientationPacket.final` as the first typed answer before replying or selecting work.",
        "   This runs `startup-context`, `session-resume`, review-channel status, and `context-graph --mode bootstrap` in order.",
        "   Stop if `final.safe_to_continue=false`, startup authority fails, or `final.next_command` requires checkpoint or repair.",
        f"2. `python3 dev/scripts/devctl.py develop next --actor {card.actor_arg} --format md`",
        "   If it returns `continuation_required`, run its `next_step_command`.",
        "   Packet audits advance through that typed next step instead of rerunning the same reducer.",
        "   Archived packet-history rows are audit evidence, not live packet-attention blockers.",
        "   Selection comes from typed plan/lifecycle authority; packet ids are intake/provenance only unless unresolved intake blocks authority.",
        "3. Diagnostic fallback commands, only when `devctl session` is unavailable or names a child command:",
        f"   `python3 dev/scripts/devctl.py startup-context --role {card.role_arg} --format json`",
        f"   `python3 dev/scripts/devctl.py session-resume --role {card.role_arg} --format bootstrap`",
        "   `python3 dev/scripts/devctl.py review-channel --action status --terminal none --format json`",
        "   `python3 dev/scripts/devctl.py context-graph --mode bootstrap --format md`",
        "",
        "## Typed authority",
        "",
        "- `StartupContext`, `SessionResume`, `ContextGraphSnapshot`, `SystemCatalog`, `ProjectGovernance`, `MasterPlan`, `PlanRow`, contracts, receipts, and guard results are typed authority.",
        "- `AgentDispatchPacket` may recommend bounded next work, but it does not grant mutation authority by itself.",
        "- `TypedAction -> ActionResult -> RunRecord -> ValidationReceipt` is the proof chain for mutations.",
        "- A typed `AgentLoopOperatorOverride` can allow scoped edit-only repair when the operator explicitly approves it; it never authorizes staging, commit, push, or raw bypass.",
        "- `system-picture` is a composite reducer; use it after startup authority is known, not as the first hop.",
        "",
        "## Projection-only surfaces",
        "",
        "- Generated markdown, bridge text, dashboard rows, mobile/status views, slash commands, and prompt files are projections or thin adapters.",
        "- `AGENTS.md` is the shared generated boot card; local peer projections route agents to typed state without overriding it.",
        "- Remote-control/dashboard handoffs must remain typed packets or plan rows; provider labels and bridge text are never authority.",
        "- Refresh generated surfaces with `python3 dev/scripts/devctl.py render-surfaces --write --format md`.",
        "- Check projection drift with `python3 dev/scripts/devctl.py docs-check --strict-tooling --format json`.",
        "",
        "## Never",
        "",
        "- Never treat generated markdown, bridge text, dashboard rows, slash commands, or memory notes as backend authority.",
        "- Memory is short-term continuity only; durable rules must live in repo-owned typed authority, policy, docs, receipts, or guards.",
        "- Never invent a raw bypass path, raw push shortcut, parallel lifecycle system, parallel finding system, or parallel developer-agent authority path.",
        "- Never treat VoiceTerm literals as portable governance authority.",
        "- Never continue editing when startup authority says checkpoint, repair, or stop.",
        "",
        "## Focused navigation",
        "",
        "- `python3 dev/scripts/devctl.py system-map --format md`",
        "- `python3 dev/scripts/devctl.py system-picture --format md`",
        "- `python3 dev/scripts/devctl.py platform-contracts --format md`",
        "- `python3 dev/scripts/devctl.py context-graph --query '<term>' --format md`",
        "- `python3 dev/scripts/devctl.py review-channel --action status --terminal none --format md`",
        "- `python3 dev/scripts/devctl.py develop campaign --format md` (remote-control, exception debt, and push-proof posture)",
        "- `python3 dev/scripts/devctl.py develop show --slice-id <id> --format md`",
        "",
        "## Active-plan onboarding (adding files under `dev/active/`)",
        "",
        "- Read `dev/active/INDEX.md` before adding or promoting active owner docs.",
        "- Add an entry in `dev/active/INDEX.md` for each new `dev/active/` file.",
        "- Run `python3 dev/scripts/checks/check_active_plan_sync.py` before handoff.",
        "",
        "## Verification before handoff",
        "",
        "- Run the task-class guard bundle selected by `python3 dev/scripts/devctl.py check-router --format md`.",
        "- Use `python3 dev/scripts/devctl.py test-python --suite devctl --path <test>` for focused Python proof instead of raw broad pytest; multi-target devctl proof is split into serial single-target sessions with measured per-target timeouts selected by `check-router`.",
        "- For generated-surface changes, run `python3 dev/scripts/devctl.py render-surfaces --format md` and `python3 dev/scripts/checks/check_instruction_surface_sync.py --format md`.",
        "- For governance/runtime contract changes, run `python3 dev/scripts/devctl.py platform-contracts --format md` and `python3 dev/scripts/checks/check_platform_contract_closure.py --format md`.",
        "- The managed ReviewSnapshot hooks are time-bounded and fail-open; freshness guards remain the proof of current receipts.",
        "- Governed checkpoint retries must restage non-receipt unstaged work instead of preserving stale partial indexes.",
        "- Governed push writes `dev/reports/push/latest_push_report.json`; legacy `latest.json` is only a read fallback.",
        "- For release or publication work, use `python3 dev/scripts/devctl.py push --execute`; raw publish proof is not a closure receipt.",
        "",
        "## Surface provenance",
        "",
        f"- contract_id: `{INSTRUCTION_BOOT_CARD_CONTRACT_ID}`",
        f"- schema_version: `{INSTRUCTION_BOOT_CARD_SCHEMA_VERSION}`",
        f"- surface_id: `{card.surface_id}`",
        f"- source_contract: `{INSTRUCTION_BOOT_CARD_CONTRACT_ID}`",
        "- source_command: `python3 dev/scripts/devctl.py render-surfaces --write --format md`",
        f"- source_path: `{card.source_path or 'repo-pack policy + typed state'}`",
        f"- repo_pack_id: `{card.repo_pack_id}`",
        f"- repo_pack_version: `{card.repo_pack_version}`",
        "- surface_provenance: `SurfaceProvenance`",
        "- projection_only: true",
        "",
    ]
    return "\n".join(lines)


def _surface_role(*, surface_id: str, output_path: str) -> tuple[str, str]:
    text = f"{surface_id} {output_path}".lower()
    if "claude" in text:
        return "implementer", "claude"
    if "codex" in text:
        return "reviewer", "codex"
    return "<role>", "<actor>"


__all__ = [
    "FORBIDDEN_BOOT_CLAIMS",
    "INSTRUCTION_BOOT_CARD_CONTRACT_ID",
    "INSTRUCTION_BOOT_CARD_SCHEMA_VERSION",
    "InstructionBootCard",
    "REQUIRED_BOOT_COMMANDS",
    "REQUIRED_BOOT_SECTIONS",
    "build_instruction_boot_card",
]
