"""Renderer for generated AI instruction boot cards."""

from __future__ import annotations

from dataclasses import dataclass


INSTRUCTION_BOOT_CARD_CONTRACT_ID = "InstructionBootCard"
INSTRUCTION_BOOT_CARD_SCHEMA_VERSION = 1

REQUIRED_BOOT_SECTIONS = (
    "This is projection-only",
    "Role and Help Discovery",
    "Run in order",
    "Typed authority",
    "Projection-only surfaces",
    "Never",
    "Focused navigation",
    "Active-plan onboarding (adding files under `dev/active/`)",
    "Verification before handoff",
)

REQUIRED_BOOT_COMMANDS = (
    "devctl.py --help",
    "session --role",
    "session --help",
    "startup-context",
    "session-resume",
    "review-channel status",
    "review-channel --action post --help",
    "context-graph --mode bootstrap",
    "context-graph --help",
    "develop next",
    "develop --help",
    "enforce-final-response-gate",
    "system-map",
    "system-picture",
    "platform-contracts",
    "render-surfaces",
    "docs-check",
    "test-python",
)

FORBIDDEN_BOOT_CLAIMS = (
    "AGENTS.md is canonical authority",
    "CLAUDE.md is canonical authority",
    "VoiceTerm is hidden default platform authority",
)

SESSION_ROLE_CHOICES = ("reviewer", "implementer", "dashboard", "observer")
FORBIDDEN_BOOT_ROLE_PLACEHOLDERS = (
    "--role <role>",
    "--role coding-agent",
    "--role codex",
)


@dataclass(frozen=True, slots=True)
class InstructionBootCard:
    """One generated bootstrap card for an AI-facing instruction surface."""

    surface_id: str
    output_path: str
    role_arg: str
    actor_arg: str
    source_path: str
    repo_pack_id: str
    repo_pack_version: str


def build_instruction_boot_card(
    *,
    surface_id: str,
    output_path: str,
    source_path: str,
    repo_pack_id: str,
    repo_pack_version: str,
) -> str:
    """Render a short projection-only bootstrap card."""
    role_arg, actor_arg = _surface_role(surface_id=surface_id, output_path=output_path)
    card = InstructionBootCard(
        surface_id=surface_id,
        output_path=output_path,
        role_arg=role_arg,
        actor_arg=actor_arg,
        source_path=source_path,
        repo_pack_id=repo_pack_id,
        repo_pack_version=repo_pack_version,
    )
    lines = [
        "# Agent Boot Card",
        "",
        "<!-- Generated by `python3 dev/scripts/devctl.py render-surfaces --write --format md`; do not edit by hand. -->",
        "",
        "## This is projection-only",
        "",
        f"- `{card.output_path}` is a generated boot card, not durable policy authority.",
        "- Durable process authority lives in typed state, active owner docs, repo-pack policy, contracts, receipts, and guards.",
        "- VoiceTerm is this repo's first-party adopter/client of the portable governance platform.",
        "- Resolve repo behavior through `ProjectGovernance`, repo-pack policy, and typed runtime contracts.",
        "",
        "## Role and Help Discovery",
        "",
        f"- Valid `--role` choices for `session`, `startup-context`, and `session-resume`: {_role_choices_text()}.",
        f"- This surface's examples use `--role {card.role_arg}` and `--actor {card.actor_arg}`; switch only when typed startup authority, operator direction, or session assignment says to.",
        "- Discover command shape before guessing: `python3 dev/scripts/devctl.py --help`.",
        "- Inspect session bootstrap help: `python3 dev/scripts/devctl.py session --help`.",
        "- Inspect packet posting help: `python3 dev/scripts/devctl.py review-channel --action post --help`.",
        "- Inspect controller and graph help: `python3 dev/scripts/devctl.py develop --help` and `python3 dev/scripts/devctl.py context-graph --help`.",
        "",
        "## Run in order",
        "",
        f"1. `python3 dev/scripts/devctl.py session --role {card.role_arg} --include-review-status always --format json`",
        "   Use `SessionOrientationPacket.final` as the first typed answer before replying or selecting work.",
        "   This runs `startup-context`, `session-resume`, review-channel status, and `context-graph --mode bootstrap` in order.",
        "   Stop if `final.safe_to_continue=false`, startup authority fails, or `final.next_command` requires checkpoint or repair.",
        f"2. `python3 dev/scripts/devctl.py develop next --actor {card.actor_arg} --format md`",
        "   If it returns `continuation_required`, run its `next_step_command`.",
        "   Packet audits advance through that typed next step instead of rerunning the same reducer.",
        "   Archived packet-history rows are audit evidence, not live packet-attention blockers.",
        "   Selection comes from typed plan/lifecycle authority; packet ids are intake/provenance only unless unresolved intake blocks authority.",
        f"3. Before any final response or `TASK_COMPLETE`, run `python3 dev/scripts/devctl.py develop next --actor {card.actor_arg} --enforce-final-response-gate --format json`.",
        "   This is the `enforce-final-response-gate` stop guard; treat a denial as typed continuation work, not permission to summarize and exit.",
        "   If the gate reports `final_response_allowed=false`, `continuation_state=must_continue`, or a `next_required_command`, do not emit final completion prose.",
        "   Run the typed next command, read the targeted inbox/body, and continue until the gate allows final response or a scoped `stop_anchor` stops the goal.",
        "   A live `continuation_anchor` is the repo-native `/goal`: Codex keeps working inside the same session instead of stopping.",
        "4. Diagnostic fallback commands, only when `devctl session` is unavailable or names a child command:",
        f"   `python3 dev/scripts/devctl.py startup-context --role {card.role_arg} --format json`",
        f"   `python3 dev/scripts/devctl.py session-resume --role {card.role_arg} --format bootstrap`",
        "   `python3 dev/scripts/devctl.py review-channel --action status --terminal none --format json`",
        "   `python3 dev/scripts/devctl.py context-graph --mode bootstrap --format md`",
        "",
        "## Typed authority",
        "",
        "- `StartupContext`, `SessionResume`, `ContextGraphSnapshot`, `SystemCatalog`, `ProjectGovernance`, `MasterPlan`, `PlanRow`, contracts, receipts, and guard results are typed authority.",
        "- `AgentDispatchPacket` may recommend bounded next work, but it does not grant mutation authority by itself.",
        "- `TypedAction -> ActionResult -> RunRecord -> ValidationReceipt` is the proof chain for mutations.",
        "- A typed `AgentLoopOperatorOverride` can allow scoped edit-only repair when the operator explicitly approves it; it never authorizes staging, commit, push, or raw bypass.",
        f"- If the final gate emits a scoped edit-only override, continue through `/develop next --actor {card.actor_arg} --operator-override --override-scope edit-only --slice-id <id>` so the override survives reducer refresh and compaction; do not replace it with raw `agent-loop` bypass.",
        "- Trusted/no-prompt provider launch authority must come from an active edit-only `BypassLifecycle` receipt (`BypassRequest -> BypassEvaluation -> BypassReceipt -> BypassExpiry`) that composes with `GovernedExceptionLifecycle`; raw `--approval-mode trusted` or bridge prose is not authority.",
        "- Session continuation after `TASK_COMPLETE` must come from `SessionTerminationPolicy`, `TaskCompleteDecision`, and actor/role/session-scoped `continuation_anchor` / `stop_anchor` packets, not packet body prose.",
        "- For autonomous multi-hour loops, set `session_termination_policy.mode=keep_awake_via_packets` before the agent can emit `TASK_COMPLETE`, and keep a scoped `continuation_anchor` live until typed controller closure allows stop.",
        "- `system-picture` is a composite reducer; use it after startup authority is known, not as the first hop.",
        "",
        "## Projection-only surfaces",
        "",
        "- Generated markdown, bridge text, dashboard rows, mobile/status views, slash commands, and prompt files are projections or thin adapters.",
        "- `AGENTS.md` is the shared generated boot card; local peer projections route agents to typed state without overriding it.",
        "- Remote-control/dashboard handoffs must remain typed packets or plan rows; provider labels and bridge text are never authority.",
        "- Automation-only review-channel follow loops emit typed frames and packets; they must not rewrite `bridge.md` heartbeat projection state.",
        "- `check_bridge_projection_only.py` is enforced through quality policy, tooling/release bundles, and CI workflows so bridge projections cannot regain backend authority.",
        "- Launcher/recovery decisions must consume typed session-liveness evidence; stale prepared metadata alone is not proof that a live conductor can be replaced.",
        "- Refresh generated surfaces with `python3 dev/scripts/devctl.py render-surfaces --write --format md`.",
        "- Check projection drift with `python3 dev/scripts/devctl.py docs-check --strict-tooling --format json`.",
        "",
        "## Never",
        "",
        "- Never treat generated markdown, bridge text, dashboard rows, slash commands, or memory notes as backend authority.",
        "- Memory is short-term continuity only; durable rules must live in repo-owned typed authority, policy, docs, receipts, or guards.",
        "- Never invent a raw bypass path, raw push shortcut, parallel lifecycle system, parallel finding system, or parallel developer-agent authority path.",
        "- Never treat VoiceTerm literals as portable governance authority.",
        "- Never continue editing when startup authority says checkpoint, repair, or stop.",
        "",
        "## Focused navigation",
        "",
        "- `python3 dev/scripts/devctl.py system-map --format md`",
        "- `python3 dev/scripts/devctl.py system-picture --format md`",
        "- `python3 dev/scripts/devctl.py platform-contracts --format md`",
        "- `python3 dev/scripts/devctl.py context-graph --query '<term>' --format md`",
        "- `python3 dev/scripts/devctl.py review-channel --action status --terminal none --format md`",
        "- `python3 dev/scripts/devctl.py develop campaign --format md` (remote-control, exception debt, and push-proof posture)",
        "- `python3 dev/scripts/devctl.py develop show --slice-id <id> --format md`",
        "",
        "## Active-plan onboarding (adding files under `dev/active/`)",
        "",
        "- Read `dev/active/INDEX.md` before adding or promoting active owner docs.",
        "- Add an entry in `dev/active/INDEX.md` for each new `dev/active/` file.",
        "- Run `python3 dev/scripts/checks/check_active_plan_sync.py` before handoff.",
        "",
        "## Verification before handoff",
        "",
        "- Run the task-class guard bundle selected by `python3 dev/scripts/devctl.py check-router --format md`.",
        "- Use `python3 dev/scripts/devctl.py test-python --suite devctl --path <test>` for focused Python proof instead of raw broad pytest; `check-router` selects measured per-target timeouts and may shard large targets with explicit node ids plus `--parallel-workers`.",
        "- Governed push preflight carries typed `ValidationScope`: standalone checks default to `live_worktree`, while authorized publication phases use `pipeline_authorized_phase` so live projection guards remain visible evidence without hard-blocking the already-authorized commit range.",
        "- Governed push publication preflight fails fast on the first blocker by default; audit-style `--keep-going` requires explicit repo policy opt-in.",
        "- Startup/work-intake projected push commands must use the same fail-fast default and may add `--keep-going` only when repo policy explicitly requests audit mode.",
        "- For generated-surface changes, run `python3 dev/scripts/devctl.py render-surfaces --format md` and `python3 dev/scripts/checks/check_instruction_surface_sync.py --format md`.",
        "- Scope-path extraction in `dev/scripts/devctl/runtime/scope_path_claims.py:_PATH_RE` recognizes both `.json` and `.jsonl` extensions, so typed-state paths such as `dev/state/plan_index.jsonl` referenced in instruction or reviewed-scope text are matched by `extract_scope_paths()` and `path_matches_scope_claim()` for the startup-authority concurrent-writer contract.",
        "- For governance/runtime contract changes, run `python3 dev/scripts/devctl.py platform-contracts --format md` and `python3 dev/scripts/checks/check_platform_contract_closure.py --format md`.",
        "- The managed pre-commit hook is a read-only commit-permission gate; post-commit ReviewSnapshot receipt hooks are time-bounded and fail-open.",
        "- Managed ReviewSnapshot/generated-surface receipt detection uses the shared receipt-prefix registry; do not add per-command receipt-prefix forks.",
        "- Codex-authored `task_produced` closure packets require commit evidence or a clean worktree; dirty-tree interim evidence must use non-closure packet kinds.",
        "- Governed checkpoint retries must restage non-receipt unstaged work instead of preserving stale partial indexes.",
        "- Governed push writes `dev/reports/push/latest_push_report.json`; legacy `latest.json` is only a read fallback.",
        "- For release or publication work, use `python3 dev/scripts/devctl.py push --execute`; raw publish proof is not a closure receipt.",
        "",
        "## Surface provenance",
        "",
        f"- contract_id: `{INSTRUCTION_BOOT_CARD_CONTRACT_ID}`",
        f"- schema_version: `{INSTRUCTION_BOOT_CARD_SCHEMA_VERSION}`",
        f"- surface_id: `{card.surface_id}`",
        f"- source_contract: `{INSTRUCTION_BOOT_CARD_CONTRACT_ID}`",
        "- source_command: `python3 dev/scripts/devctl.py render-surfaces --write --format md`",
        f"- source_path: `{card.source_path or 'repo-pack policy + typed state'}`",
        f"- repo_pack_id: `{card.repo_pack_id}`",
        f"- repo_pack_version: `{card.repo_pack_version}`",
        "- surface_provenance: `SurfaceProvenance`",
        "- projection_only: true",
        "",
    ]
    return "\n".join(lines)


def _surface_role(*, surface_id: str, output_path: str) -> tuple[str, str]:
    text = f"{surface_id} {output_path}".lower()
    if "claude" in text:
        return "implementer", "claude"
    if "codex" in text or "agents_boot_card" in text or "agents.md" in text:
        return "reviewer", "codex"
    return "reviewer", "codex"


def _role_choices_text() -> str:
    head = ", ".join(f"`{role}`" for role in SESSION_ROLE_CHOICES[:-1])
    return f"{head}, or `{SESSION_ROLE_CHOICES[-1]}`"


__all__ = [
    "FORBIDDEN_BOOT_CLAIMS",
    "FORBIDDEN_BOOT_ROLE_PLACEHOLDERS",
    "INSTRUCTION_BOOT_CARD_CONTRACT_ID",
    "INSTRUCTION_BOOT_CARD_SCHEMA_VERSION",
    "InstructionBootCard",
    "REQUIRED_BOOT_COMMANDS",
    "REQUIRED_BOOT_SECTIONS",
    "SESSION_ROLE_CHOICES",
    "build_instruction_boot_card",
]
