name: Documentation

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".markdownlintignore"
      - ".github/workflows/docs_lint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".markdownlintignore"
      - ".github/workflows/docs_lint.yml"

permissions:
  contents: read

concurrency:
  group: documentation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "20"
      - run: npm install --global markdownlint-cli@0.45.0
      - name: Lint product documentation
        run: >-
          markdownlint
          -c .markdownlint.yaml
          -p .markdownlintignore
          README.md QUICK_START.md CHANGELOG.md
          guides/*.md scripts/*.md scripts/tests/*.md
          pypi/*.md app/*.md
          .github/*.md .github/ISSUE_TEMPLATE/*.md
          .github/PULL_REQUEST_TEMPLATE/*.md .github/workflows/README.md
